<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Olalla Díaz-Yáñez">
<meta name="author" content="Laura Dobor">
<meta name="author" content="Katarina Merganicova">
<meta name="author" content="Mats Nieberg">

<title>Forest Modeling Exercises</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="modelEx_files/libs/clipboard/clipboard.min.js"></script>
<script src="modelEx_files/libs/quarto-html/quarto.js"></script>
<script src="modelEx_files/libs/quarto-html/popper.min.js"></script>
<script src="modelEx_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="modelEx_files/libs/quarto-html/anchor.min.js"></script>
<link href="modelEx_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="modelEx_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="modelEx_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="modelEx_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="modelEx_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-overview" id="toc-sec-overview" class="nav-link active" data-scroll-target="#sec-overview">Overview</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#sec-dataDescription" id="toc-sec-dataDescription" class="nav-link" data-scroll-target="#sec-dataDescription">Data description</a></li>
  </ul></li>
  <li><a href="#species-description" id="toc-species-description" class="nav-link" data-scroll-target="#species-description">Species description</a>
  <ul class="collapse">
  <li><a href="#species-1---bryophytes" id="toc-species-1---bryophytes" class="nav-link" data-scroll-target="#species-1---bryophytes">Species 1 - Bryophytes</a></li>
  <li><a href="#species-2---great-spotted-woodpecker-dendrocopos-major" id="toc-species-2---great-spotted-woodpecker-dendrocopos-major" class="nav-link" data-scroll-target="#species-2---great-spotted-woodpecker-dendrocopos-major">Species 2 - Great spotted woodpecker (<strong>Dendrocopos major</strong>)</a></li>
  <li><a href="#species-3---eurasian-treecreeper" id="toc-species-3---eurasian-treecreeper" class="nav-link" data-scroll-target="#species-3---eurasian-treecreeper">Species 3 - Eurasian treecreeper</a></li>
  </ul></li>
  <li><a href="#models" id="toc-models" class="nav-link" data-scroll-target="#models">Models</a>
  <ul class="collapse">
  <li><a href="#generalized-linear-models-glms" id="toc-generalized-linear-models-glms" class="nav-link" data-scroll-target="#generalized-linear-models-glms">Generalized Linear Models (GLMs)</a></li>
  <li><a href="#sec-modelBRT" id="toc-sec-modelBRT" class="nav-link" data-scroll-target="#sec-modelBRT">Boosted regression trees (BRTs)</a></li>
  </ul></li>
  <li><a href="#the-exercise" id="toc-the-exercise" class="nav-link" data-scroll-target="#the-exercise">The exercise</a>
  <ul class="collapse">
  <li><a href="#the-project-folder" id="toc-the-project-folder" class="nav-link" data-scroll-target="#the-project-folder">The project folder</a></li>
  <li><a href="#download-the-data" id="toc-download-the-data" class="nav-link" data-scroll-target="#download-the-data">Download the data</a></li>
  <li><a href="#explore-the-data" id="toc-explore-the-data" class="nav-link" data-scroll-target="#explore-the-data">Explore the data</a></li>
  <li><a href="#sec-q1" id="toc-sec-q1" class="nav-link" data-scroll-target="#sec-q1">Question 1</a>
  <ul class="collapse">
  <li><a href="#fitting-a-poisson-glm-in-r" id="toc-fitting-a-poisson-glm-in-r" class="nav-link" data-scroll-target="#fitting-a-poisson-glm-in-r">Fitting a Poisson GLM in R</a></li>
  <li><a href="#explanatory-power-of-the-model" id="toc-explanatory-power-of-the-model" class="nav-link" data-scroll-target="#explanatory-power-of-the-model">Explanatory Power of the model</a></li>
  <li><a href="#model-assumptions" id="toc-model-assumptions" class="nav-link" data-scroll-target="#model-assumptions">Model Assumptions</a></li>
  </ul></li>
  <li><a href="#sec-q2" id="toc-sec-q2" class="nav-link" data-scroll-target="#sec-q2">Question 2</a>
  <ul class="collapse">
  <li><a href="#fitting-a-poisson-glm-in-r-1" id="toc-fitting-a-poisson-glm-in-r-1" class="nav-link" data-scroll-target="#fitting-a-poisson-glm-in-r-1">Fitting a Poisson GLM in R</a></li>
  <li><a href="#explanatory-power-of-the-model-1" id="toc-explanatory-power-of-the-model-1" class="nav-link" data-scroll-target="#explanatory-power-of-the-model-1">Explanatory Power of the model</a></li>
  <li><a href="#model-assumptions-1" id="toc-model-assumptions-1" class="nav-link" data-scroll-target="#model-assumptions-1">Model Assumptions</a></li>
  </ul></li>
  <li><a href="#sec-q3" id="toc-sec-q3" class="nav-link" data-scroll-target="#sec-q3">Question 3</a>
  <ul class="collapse">
  <li><a href="#fitting-a-poisson-glm-in-r-2" id="toc-fitting-a-poisson-glm-in-r-2" class="nav-link" data-scroll-target="#fitting-a-poisson-glm-in-r-2">Fitting a Poisson GLM in R</a></li>
  <li><a href="#explanatory-power-of-the-model-2" id="toc-explanatory-power-of-the-model-2" class="nav-link" data-scroll-target="#explanatory-power-of-the-model-2">Explanatory Power of the model</a></li>
  <li><a href="#model-assumptions-2" id="toc-model-assumptions-2" class="nav-link" data-scroll-target="#model-assumptions-2">Model Assumptions</a></li>
  </ul></li>
  <li><a href="#sec-q4" id="toc-sec-q4" class="nav-link" data-scroll-target="#sec-q4">Question 4</a>
  <ul class="collapse">
  <li><a href="#fitting-a-poisson-glm-in-r-3" id="toc-fitting-a-poisson-glm-in-r-3" class="nav-link" data-scroll-target="#fitting-a-poisson-glm-in-r-3">Fitting a Poisson GLM in R</a></li>
  <li><a href="#explanatory-power-of-the-model-3" id="toc-explanatory-power-of-the-model-3" class="nav-link" data-scroll-target="#explanatory-power-of-the-model-3">Explanatory Power of the model</a></li>
  <li><a href="#model-assumptions-3" id="toc-model-assumptions-3" class="nav-link" data-scroll-target="#model-assumptions-3">Model Assumptions</a></li>
  </ul></li>
  <li><a href="#sec-q5" id="toc-sec-q5" class="nav-link" data-scroll-target="#sec-q5">Question 5</a>
  <ul class="collapse">
  <li><a href="#fitting-a-brt-in-r" id="toc-fitting-a-brt-in-r" class="nav-link" data-scroll-target="#fitting-a-brt-in-r">Fitting a BRT in R</a></li>
  <li><a href="#model-behaviour" id="toc-model-behaviour" class="nav-link" data-scroll-target="#model-behaviour">Model behaviour</a></li>
  <li><a href="#model-output-analysis" id="toc-model-output-analysis" class="nav-link" data-scroll-target="#model-output-analysis">Model output analysis</a></li>
  </ul></li>
  <li><a href="#sec-q6" id="toc-sec-q6" class="nav-link" data-scroll-target="#sec-q6">Question 6</a>
  <ul class="collapse">
  <li><a href="#fitting-a-brt-in-r-1" id="toc-fitting-a-brt-in-r-1" class="nav-link" data-scroll-target="#fitting-a-brt-in-r-1">Fitting a BRT in R</a></li>
  <li><a href="#model-behaviour-1" id="toc-model-behaviour-1" class="nav-link" data-scroll-target="#model-behaviour-1">Model behaviour</a></li>
  <li><a href="#model-output-analysis-1" id="toc-model-output-analysis-1" class="nav-link" data-scroll-target="#model-output-analysis-1">Model output analysis</a></li>
  </ul></li>
  <li><a href="#sec-q7" id="toc-sec-q7" class="nav-link" data-scroll-target="#sec-q7">Question 7</a>
  <ul class="collapse">
  <li><a href="#fitting-a-brt-in-r-2" id="toc-fitting-a-brt-in-r-2" class="nav-link" data-scroll-target="#fitting-a-brt-in-r-2">Fitting a BRT in R</a></li>
  <li><a href="#model-behaviour-2" id="toc-model-behaviour-2" class="nav-link" data-scroll-target="#model-behaviour-2">Model behaviour</a></li>
  <li><a href="#model-output-analysis-2" id="toc-model-output-analysis-2" class="nav-link" data-scroll-target="#model-output-analysis-2">Model output analysis</a></li>
  </ul></li>
  <li><a href="#sec-q8" id="toc-sec-q8" class="nav-link" data-scroll-target="#sec-q8">Question 8</a>
  <ul class="collapse">
  <li><a href="#fitting-a-brt-in-r-3" id="toc-fitting-a-brt-in-r-3" class="nav-link" data-scroll-target="#fitting-a-brt-in-r-3">Fitting a BRT in R</a></li>
  <li><a href="#model-behaviour-3" id="toc-model-behaviour-3" class="nav-link" data-scroll-target="#model-behaviour-3">Model behaviour</a></li>
  <li><a href="#model-output-analysis-3" id="toc-model-output-analysis-3" class="nav-link" data-scroll-target="#model-output-analysis-3">Model output analysis</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Forest Modeling Exercises</h1>
<p class="subtitle lead">Process based and empirical modeling</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Olalla Díaz-Yáñez </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            ETH Zurich (olalla.diaz@usys.ethz.ch)
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Laura Dobor </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            CZU (laura.dobor@gmail.com)
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Katarina Merganicova </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            CZU (merganicova@fld.czu.cz)
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Mats Nieberg </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            PIK-Potsdam | EFI (mats.nieberg@pik-potsdam.de)
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

</header>

<section id="sec-overview" class="level1">
<h1>Overview</h1>
<p>This document is the instructions of the empirical modeling group assignments. We will cover two examples of creating two models based on observed data. We will use two approaches Generalized Linear Models (GLMs) and Boosted Regression trees (BRTs).</p>
<p>Please take all the results with a grain of salt, we are making very generalized statements from a limited data set, and we are not getting into the details of how each of the models should be assessed; the goal here is that you learn how observed data can be used to create models that help you to understand the data and relationships better.</p>
<p>This document describes all the exercises, but your group has been assigned to only one, including one specific modeling approach. Each group has two questions to be answered (one question per subgroup inside each group). Please get in touch with your group coach if you are unsure what section you should focus on. The table below summarizes and links to the different parts of this document:</p>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 33%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th>Sub</th>
<th>Question number</th>
<th>Question</th>
<th>Approach</th>
<th>Go to section</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>3</td>
<td>1</td>
<td>Does a more diverse forest in structure and composition have more Bryophites species?</td>
<td>GLM</td>
<td><a href="#sec-q1">Section&nbsp;5.4</a></td>
</tr>
<tr class="even">
<td>1</td>
<td>4</td>
<td>2</td>
<td>Is the number of Bryophites species affected by forest management type and the forest structural diversity?</td>
<td>GLM</td>
<td><a href="#sec-q2">Section&nbsp;5.5</a></td>
</tr>
<tr class="odd">
<td>2</td>
<td>3</td>
<td>3</td>
<td>Does a more diverse forest in structure and composition have more bird species?</td>
<td>GLM</td>
<td><a href="#sec-q3">Section&nbsp;5.6</a></td>
</tr>
<tr class="even">
<td>2</td>
<td>4</td>
<td>4</td>
<td>Is the number of bird species affected by forest management type and the forest structural diversity?</td>
<td>GLM</td>
<td><a href="#sec-q4">Section&nbsp;5.7</a></td>
</tr>
<tr class="odd">
<td>3</td>
<td>3</td>
<td>5</td>
<td>Is the presence of the Great spotted woodpecker affected by forest density?</td>
<td>BRT</td>
<td><a href="#sec-q5">Section&nbsp;5.8</a></td>
</tr>
<tr class="even">
<td>3</td>
<td>4</td>
<td>6</td>
<td>Is the presence of the Great spotted woodpecker affected by forest diversity?</td>
<td>BRT</td>
<td><a href="#sec-q6">Section&nbsp;5.9</a></td>
</tr>
<tr class="odd">
<td>4</td>
<td>3</td>
<td>7</td>
<td>Is the presence of the Eurasian treecreeper affected by forest density?</td>
<td>BRT</td>
<td><a href="#sec-q7">Section&nbsp;5.10</a></td>
</tr>
<tr class="even">
<td>4</td>
<td>4</td>
<td>8</td>
<td>Is the presence of the Eurasian treecreeper affected by forest management?</td>
<td>BRT</td>
<td><a href="#sec-q8">Section&nbsp;5.11</a></td>
</tr>
</tbody>
</table>
</section>
<section id="data" class="level1">
<h1>Data</h1>
<p>We will work with one dataset derived from the inventory developed to assess forest structure and deadwood properties of six representative forest areas in the Czech Republic <span class="citation" data-cites="hosek">(<a href="#ref-hosek" role="doc-biblioref">Hošek, n.d.</a>)</span>. This dataset collects observations of the presence /absence of certain species of biodiversity importance across 99 plots.</p>
<p>The data was collected from square sampling plots (2500 m2 each) in six forested Czech Republic regions. These regions are representative of the main bio-regions and elevation range of forests, considering their importance in territorial representation, forestry, and ecology. The inventory sampled for biodiversity variables such as the presence/absence of different species of birds, Tracheophyta, bryophytes, fungi, lichens, and beetles.</p>
<p>The dataset has been generously provided by XXXXXX to be used in the context of this exercise. It should not be used for other purposes or be further distributed. If you want to use this data or learn more about it, please get in touch with XXXX here: XXXX.</p>
<p>The data you can download for this exercise is an aggregated summary of the original data, some aspects have been modified from the observed data, so the results you will obtain will only partially match the observed reality. This data is very similar in structure and observed variables to the one you collected in this summer school. The idea is to move from data collection, analysis to this part, where you use the data to create a model.</p>
<section id="sec-dataDescription" class="level2">
<h2 class="anchored" data-anchor-id="sec-dataDescription">Data description</h2>
<p>These are the variables available in the data</p>
<ul>
<li><code>longitud</code>: longitude of the plot location</li>
<li><code>latitude</code>: latitude of the plot location</li>
<li><code>forestManagementType</code>: forest management type applied in this plot</li>
<li><code>forestStructure</code>: current forest structure in the plot</li>
<li><code>slope</code>: slope of the plot</li>
<li><code>A.pseudoplatanus</code>: proportion of this tree species in the plot in volume</li>
<li><code>F.sylvatica</code>: proportion of this tree species in the plot in volume</li>
<li><code>L.decidua</code>: proportion of this tree species in the plot in volume</li>
<li><code>Q.robur</code>: proportion of this tree species in the plot in volume</li>
<li><code>S.aucuparia</code> : proportion of this tree species in the plot in volume</li>
<li><code>B.pendula</code>: proportion of this tree species in the plot in volume</li>
<li><code>P.abies</code>: proportion of this tree species in the plot in volume</li>
<li><code>P.sylvestris</code>: proportion of this tree species in the plot in volume</li>
<li><code>F.excelsior</code>: proportion of this tree species in the plot in volume</li>
<li><code>A.alba</code>: proportion of this tree species in the plot in volume</li>
<li><code>A.platanoides</code>: proportion of this tree species in the plot in volume</li>
<li><code>T.cordata</code>: proportion of this tree species in the plot in volume</li>
<li><code>S.racemosa</code>: proportion of this tree species in the plot in volume</li>
<li><code>U.glabra</code>: proportion of this tree species in the plot in volume</li>
<li><code>S.nigra</code>: proportion of this tree species in the plot in volume</li>
<li><code>P.alba</code>: proportion of this tree species in the plot in volume</li>
<li><code>U.minor</code>: proportion of this tree species in the plot in volume</li>
<li><code>S.caprea</code>: proportion of this tree species in the plot in volume</li>
<li><code>C.betulus</code>: proportion of this tree species in the plot in volume</li>
<li><code>P.nigra</code>: proportion of this tree species in the plot in volume</li>
<li><code>Q.petraea</code>: proportion of this tree species in the plot in volume</li>
<li><code>S.torminalis</code>: proportion of this tree species in the plot in volume</li>
<li><code>A.campestre</code>: proportion of this tree species in the plot in volume</li>
<li><code>P.strobus</code>: proportion of this tree species in the plot in volume</li>
<li><code>Q.rubra</code>: proportion of this tree species in the plot in volume</li>
<li><code>volAllha</code>: total volume in the plot</li>
<li><code>GiniDBH</code>: Gini index calculated to assess the forest structural diversity in diamter sizes, higher values indicate more structural heterogeneity; lower values indicate more homogeneous stands</li>
<li><code>ShannonIndexTreeSpp</code>: The Shannon index is way to measure the diversity of tree species in the plot</li>
<li><code>Tracheophyta_rich</code>: Species richness across Tracheophyta species</li>
<li><code>Birds_rich</code>: Species richness across Birds species</li>
<li><code>Bryophytes_rich</code> : Species richness across Bryophytes species</li>
<li><code>Fungi_rich</code>: Species richness across Fungi species</li>
<li><code>Lichens_rich</code>: Species richness across Lichens species</li>
<li><code>Beetles_rich</code>: Species richness across Beetles species</li>
<li><code>dendrocoposMajor</code>: presence / absence of Dendrocopos major</li>
<li><code>certhia</code>: presence / absence of Certhia familiaris</li>
<li><code>bryophitaNumObs</code>: number of observed Bryophytes species</li>
<li><code>birdNumObs</code>: number of observed Bird species</li>
<li><code>PlotID</code>: ID number for the plot</li>
</ul>
</section>
</section>
<section id="species-description" class="level1">
<h1>Species description</h1>
<section id="species-1---bryophytes" class="level2">
<h2 class="anchored" data-anchor-id="species-1---bryophytes">Species 1 - Bryophytes</h2>
<p>Bryophytes constitute an important and permanent component of the forest flora and diversity. They colonize various substrates, which are unsuitable for vascular plants, because of low light intensity or low nutrient level, such as deadwood, bark, rocks, and open soil. They provide shelter habitats, food, and nest material for many animals.</p>
<p>In forests, different ecological guilds of bryophytes can be distinguished by the substrate on which they are growing, including terricolous, lignicolous, corticolous and saxicolous species that occur on soil, deadwood, bark of living trees and shrubs, or rocks, respectively. As diversity and quality of these substrates is affected by forest management, bryophytes are suitable indicators for the effect of management on forest conditions. Especially typical woodland bryophytes, which are strictly depending on forest conditions. It is interesting to better understand the relation of forest management effects on bryophytes and some studies have already demonstrated their sensitivity to management practices.</p>
</section>
<section id="species-2---great-spotted-woodpecker-dendrocopos-major" class="level2">
<h2 class="anchored" data-anchor-id="species-2---great-spotted-woodpecker-dendrocopos-major">Species 2 - Great spotted woodpecker (<strong>Dendrocopos major</strong>)</h2>
<p>The&nbsp;great spotted woodpecker&nbsp;(<em>Dendrocopos major</em>) is a medium-sized&nbsp;woodpecker&nbsp;with pied black and white plumage and a red patch on the lower belly. It is found in a wide variety of woodlands,&nbsp;broadleaf,&nbsp;coniferous or mixed forests. The great spotted woodpecker spends much of its time climbing trees. It a quite generalist bird species.</p>
</section>
<section id="species-3---eurasian-treecreeper" class="level2">
<h2 class="anchored" data-anchor-id="species-3---eurasian-treecreeper">Species 3 - Eurasian treecreeper</h2>
<p>The Eurasian treecreeper or common treecreeper (Certhia familiaris) is a small passerine bird. It prefers mature trees, and in most of Europe, it tends to be found mainly in coniferous forest, especially spruce and fir.</p>
</section>
</section>
<section id="models" class="level1">
<h1>Models</h1>
<section id="generalized-linear-models-glms" class="level2">
<h2 class="anchored" data-anchor-id="generalized-linear-models-glms">Generalized Linear Models (GLMs)</h2>
<p>We propose to use a generalized linear model (GLM) to understand the abundance of different bryophytes species in the 99 plots. Count data often conform to a Poisson distribution; in this case, we have a count of the number of species recorded at each plot.</p>
<p>Fitting a Poisson GLM in R is similar to analyzing covariance (or linear model), except that we now need to use the glm function. To run a GLM, we need to provide one extra piece of information beyond that required for a linear model: the family of models we want to use. In this case, we want a Poisson family, family=poisson.</p>
</section>
<section id="sec-modelBRT" class="level2">
<h2 class="anchored" data-anchor-id="sec-modelBRT">Boosted regression trees (BRTs)</h2>
<p>Boosted regression trees (BRT) are a combination of two powerful statistical techniques: boosting and regression trees. Boosting is a machine learning technique similar to model averaging, where the results of several competing models are merged. Unlike model averaging, however, boosting uses a forward, stage-wise procedure, where tree models are fitted iteratively to a subset of the training data. Subsets of the training data used at each iteration of the model fit are randomly selected without replacement, where the proportion of the training data used is determined by the modeler, this is defined with the “bag fraction” parameter. This procedure, known as stochastic gradient boosting, introduces an element of stochasticity that improves model accuracy and reduces overfitting <span class="citation" data-cites="elith2008">(<a href="#ref-elith2008" role="doc-biblioref">Elith, Leathwick, and Hastie 2008</a>)</span>.</p>
<p>The BRT model calibration is defined by four parameters:</p>
<ul>
<li><p>the <code>learning rate</code> (or shrinkage parameter): The learning rate determines the contribution of each new tree to the growing model, and it is always substantially lower than 1, higher values being related to faster learning.</p></li>
<li><p>the <code>bag fraction</code>: The bag fraction provides in- formation on which fraction of the entire data should be drawn randomly to fit the new tree. This parameter includes a random probabilistic component, making each run model different, and is aimed at improving model accuracy, speed of model creation, and the reduction of overfitting <span class="citation" data-cites="friedman">(<a href="#ref-friedman" role="doc-biblioref">Friedman, Hastie, and Tibshirani, n.d.</a>)</span>.</p></li>
<li><p>the <code>tree complexity</code>: Tree complexity controls the number of fitted interactions among variables, and determines the number of splits in each tree; for example, a value of 1 will present only one split, meaning that the model does not consider interactions; a value of 2 will result in two splits, and two interactions.</p></li>
<li><p>The <code>number of trees</code> required for optimal prediction: The optimal number of trees is selected based on the three previous parameters. The values fitted by the final model are computed as the sum of all of the predictions of the trees, multiplied by their respective learning rates.</p></li>
</ul>
</section>
</section>
<section id="the-exercise" class="level1">
<h1>The exercise</h1>
<section id="the-project-folder" class="level2">
<h2 class="anchored" data-anchor-id="the-project-folder">The project folder</h2>
<p>All the project is available in a github repository. You can download the project with this document, code, the <code>.rproj</code> and the correct folder structure in <a href="https://github.com/oldiya/summerSchoolExercise">here [2]</a>.</p>
<p>[2] https://github.com/oldiya/summerSchoolExercise</p>
<p>In this project you will find a folder called <code>code</code> where the codes for each question are storaged. A folder called <code>data</code> where you have to storage the data that you have downloaded. A folder called <code>exercise</code>, that contains this document and all the required files to build it.</p>
</section>
<section id="download-the-data" class="level2">
<h2 class="anchored" data-anchor-id="download-the-data">Download the data</h2>
<p>You can download the data in <a href="https://polybox.ethz.ch/index.php/s/qERYKjzmFTr81Sq">here [1]</a></p>
<p>[1] https://polybox.ethz.ch/index.php/s/qERYKjzmFTr81Sq</p>
<p>Our recommendation is that you follow this folder structure and you put the data in the folder data of the project and the <code>.rproj</code> into the main folder. If you decide to organized things in a different way then you will have to change the path to the code provided to load the data in the section “Explore the data”</p>
<p><img src="images/folderStruc.png" class="img-fluid" width="300"></p>
</section>
<section id="explore-the-data" class="level2">
<h2 class="anchored" data-anchor-id="explore-the-data">Explore the data</h2>
<p>You can load the data in R by doing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>observations <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/observations.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once you have obtained the data, your next step is to explore it. It is important to carefully analyze the structure of the data and understand its meaning. Each variable must be examined closely, along with the data structure. Remember that each row in this dataset represents one plot, identified by its <code>PlotID</code>, and each column represents one variable.</p>
<p>You can explore each of the variables by doing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(observations)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   99 obs. of  45 variables:
 $ X                   : int  1 2 3 4 5 6 7 8 9 10 ...
 $ longitud            : num  13.5 13.5 13.5 13.6 13.6 ...
 $ latitude            : num  49.5 49.5 49.5 49.5 49.5 ...
 $ forestManagementType: chr  "simple clearcutting" "simple clearcutting" "simple clearcutting" "simple clearcutting" ...
 $ forestStructure     : chr  "even-aged" "even-aged" "even-aged" "even-aged" ...
 $ slope               : num  16.85 6.51 4.91 5.55 14.55 ...
 $ A.pseudoplatanus    : int  0 0 0 0 0 4 1 7 16 0 ...
 $ F.sylvatica         : int  61 0 0 100 0 82 85 91 75 0 ...
 $ L.decidua           : int  38 0 0 0 4 6 0 0 0 0 ...
 $ Q.robur             : int  0 1 0 0 0 0 0 0 0 0 ...
 $ S.aucuparia         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ B.pendula           : int  0 0 1 0 28 0 0 0 0 0 ...
 $ P.abies             : int  0 99 93 0 30 0 0 0 8 99 ...
 $ P.sylvestris        : int  0 0 7 0 1 0 0 0 0 0 ...
 $ F.excelsior         : int  0 0 0 0 38 0 0 0 0 0 ...
 $ A.alba              : int  0 0 0 0 0 4 0 0 0 1 ...
 $ A.platanoides       : int  0 0 0 0 0 2 2 2 0 0 ...
 $ T.cordata           : int  0 0 0 0 0 2 12 0 0 0 ...
 $ S.racemosa          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ U.glabra            : int  0 0 0 0 0 0 0 0 1 0 ...
 $ S.nigra             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ P.alba              : int  0 0 0 0 0 0 0 0 0 0 ...
 $ U.minor             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ S.caprea            : int  0 0 0 0 0 0 0 0 0 0 ...
 $ C.betulus           : int  0 0 0 0 0 0 0 0 0 0 ...
 $ P.nigra             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Q.petraea           : int  0 0 0 0 0 0 0 0 0 0 ...
 $ S.torminalis        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ A.campestre         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ P.strobus           : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Q.rubra             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ volAllha            : num  592 377 438 615 194 ...
 $ GiniDBH             : num  0.448 0.416 0.12 0.133 0.378 ...
 $ ShannonIndexTreeSpp : num  0.68 0.07 0.28 0 1.28 0.78 0.54 0.39 0.75 0.06 ...
 $ Tracheophyta_rich   : num  0.218 0.233 0.209 0.189 0.354 ...
 $ Birds_rich          : num  0.358 0.46 0.485 0.307 0.383 ...
 $ Bryophytes_rich     : num  0.0876 0.0876 NA 0.2629 0.3505 ...
 $ Fungi_rich          : num  0.199 0.133 0.114 0.218 0.262 ...
 $ Lichens_rich        : num  0.0659 0.1976 0.1318 0.1537 0.1537 ...
 $ Beetles_rich        : num  0.16 0.16 0.234 0.258 0.221 ...
 $ dendrocoposMajor    : int  1 1 1 0 1 1 1 1 1 1 ...
 $ certhia             : int  0 0 0 0 0 0 1 0 1 0 ...
 $ bryophitaNumObs     : int  1 1 0 3 4 5 7 4 7 1 ...
 $ birdNumObs          : int  14 18 19 12 15 14 12 14 18 18 ...
 $ PlotID              : int  1 2 3 4 5 6 7 8 9 10 ...</code></pre>
</div>
</div>
<p>You have a description of each of the variables in the section <a href="#sec-dataDescription">Section&nbsp;2.1</a>.</p>
<p>You could do further analysis by exploring the data correlations and you can even plot them to explore their values and ranges better. During this process you should start thinking:</p>
<ul>
<li>What am I trying to understand with this model? (your question)</li>
<li>What variables are important to answer my question?</li>
</ul>
<p>You could for example explore the behavior of the variables by plotting a scatterplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(<span class="sc">~</span>F.sylvatica <span class="sc">+</span> P.sylvestris <span class="sc">+</span> latitude <span class="sc">+</span> volAllha <span class="sc">+</span>  GiniDBH <span class="sc">+</span> ShannonIndexTreeSpp <span class="sc">+</span> Bryophytes_rich, </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> observations, <span class="at">main =</span> <span class="st">"Scatterplot Matrix"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/explore%20data%202-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>You can also create individual scatterplots or histograms for a variable of interest, for example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Divide the screen in 1 line and 3 columns</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">oma =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>)) </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Make the margin around each graph a bit smaller</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram and Scatterplot</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(observations<span class="sc">$</span>bryophitaNumObs, <span class="at">main =</span> <span class="st">""</span>, <span class="at">breaks =</span> <span class="dv">10</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rgb</span>(<span class="fl">0.3</span>, <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="fl">0.4</span>) , </span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Number of observed bryophita"</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> observations<span class="sc">$</span>bryophitaNumObs, </span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">x =</span> observations<span class="sc">$</span>GiniDBH,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">""</span> , <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">cex =</span> <span class="fl">0.4</span>, <span class="at">col =</span> <span class="fu">rgb</span>(<span class="fl">0.3</span>, <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="fl">0.4</span>), </span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Ginni index"</span>, <span class="at">ylab =</span> <span class="st">"Number of observed bryophita"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/example%20scatterplot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="sec-q1" class="level2">
<h2 class="anchored" data-anchor-id="sec-q1">Question 1</h2>
<ul>
<li>Does a more diverse forest in structure and composition have more Bryophytes species?</li>
</ul>
<section id="fitting-a-poisson-glm-in-r" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-poisson-glm-in-r">Fitting a Poisson GLM in R</h3>
<p>During your data exploration, you should have selected your response variable, <code>bryophitaNumObs</code>. In this case, since we are trying to understand forest structure and composition, you should also choose explanatory variables for that, such as <code>GiniDBH,</code> which indicates the forest structural diversity in diameter sizes; higher values indicate more structural heterogeneity, and lower values indicate more homogeneous stands, or the <code>ShannonIndexTreeSpp</code> which assess the diversity of tree species in the plot.</p>
<p>We could start by only looking at how the forest structural diversity affects the number of Bryophytes species that we have in a plot. You can create a GLM model with <code>bryophitaNumObs</code> as the response variable and <code>GiniDBH</code> as an explanatory variable. You will use the function glm in R and the <code>family = poisson</code>. You can see how to create and see this model here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>bryoModel1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(bryophitaNumObs <span class="sc">~</span> GiniDBH,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> poisson,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> observations)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bryoModel1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = bryophitaNumObs ~ GiniDBH, family = poisson, data = observations)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.4627     0.1388   3.333 0.000859 ***
GiniDBH       2.2797     0.4221   5.401 6.64e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 188.58  on 98  degrees of freedom
Residual deviance: 159.92  on 97  degrees of freedom
AIC: 424.2

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Here you can see that the coefficient table produced by a GLM is very similar to a linear model. The intercept tells us the estimated value of the response variable when the continuous explanatory variables (here, just the Gini index) has a value of 0. We then also have coefficients describing the slope of the relationship with our continuous explanatory variables. We can see here that the number of Bryophytes species appears to show a positive relationship with the Gini index, which means that increasing structural diversity in tree diameter sizes has a positive relationship with the number of Bryophytes species in the plot.</p>
<p>We are also interested in understanding the relationship between the number of Bryophytes species and the tree species diversity; we can now try to add this variable into the model and see if it helps us to understand things. You can do that by adding the variable <code>ShannonIndexTreeSpp</code> to the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>bryoModel2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(bryophitaNumObs <span class="sc">~</span> GiniDBH <span class="sc">+</span> ShannonIndexTreeSpp,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> poisson,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> observations)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bryoModel2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = bryophitaNumObs ~ GiniDBH + ShannonIndexTreeSpp, 
    family = poisson, data = observations)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)          0.45277    0.14060   3.220  0.00128 ** 
GiniDBH              2.17411    0.46413   4.684 2.81e-06 ***
ShannonIndexTreeSpp  0.09209    0.16202   0.568  0.56977    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 188.58  on 98  degrees of freedom
Residual deviance: 159.60  on 96  degrees of freedom
AIC: 425.88

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Here we can see that the variable Shannon index also has a positive relationship with the number of Bryophytes species in the plot, but its effect is much smaller. We can also observe that this variable is not significant. This does not mean it is wrong to add this variable because we want to understand its effect, but keeping this variable in the model depends on what you’re trying to do and what “reality” is. Adding variables that are not needed will not help your model (particularly your estimates) but also might not matter much (e.g., predictions). However, removing actual variables can create a useless model even if they don’t meet significance.</p>
<p>Variable selection is a long and complicated topic. Some general rules of thumb include: (1) Include the variable if it is of interest, (2) Include the variable if you have some prior knowledge that it should be relevant. This can be misleading because it’s a confirmation bias, but in most cases, this makes sense. (3) If you want a model that can generalize to many cases, you should favor fewer variables.</p>
</section>
<section id="explanatory-power-of-the-model" class="level3">
<h3 class="anchored" data-anchor-id="explanatory-power-of-the-model">Explanatory Power of the model</h3>
<p>When we ran linear models, we used the coefficient of determination, or R<sup>2</sup>&nbsp;to assess how much of the variability in our response variable is explained by a given model. R<sup>2</sup>&nbsp;is based on the sums of squares of our model, and so cannot be calculated for GLMs. Instead, we can calculate the deviance explained by our model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the null and residual deviance from the model</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>dev.null <span class="ot">&lt;-</span> bryoModel1<span class="sc">$</span>null.deviance</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>dev.resid <span class="ot">&lt;-</span> bryoModel1<span class="sc">$</span>deviance</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the deviance explained by the model</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>dev.explained <span class="ot">&lt;-</span> (dev.null <span class="sc">-</span> dev.resid)<span class="sc">/</span>dev.null</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Round to 3 decimal places</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>dev.explained <span class="ot">&lt;-</span> <span class="fu">round</span>(dev.explained, <span class="dv">3</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>dev.explained</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.152</code></pre>
</div>
</div>
<p>Variability in forest structure (Gini index) explain 15% of the variation in Bryophytes species richness in this study. That is an ok explanatory power for a very simple model of a complex ecological system (many factors determine the species richness for Bryophytes and we are attempting to explain everything with just one variable).</p>
</section>
<section id="model-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="model-assumptions">Model Assumptions</h3>
<p>For Poisson GLMs, there is one further assumption that we have not encountered before. If data follow a Poisson distribution, then the mean of the distribution is equal to the variance. Accordingly, a Poisson distribution is represented by just one parameter λ, which describes both the mean and the variance of the distribution.</p>
<p>Count data in ecology are often&nbsp;<strong>overdispersed</strong>, where the variance is greater than the mean. This violates the assumption of a Poisson GLM, and means that any statistics that we calculate from the model may be unreliable.</p>
<p>We can get an indication of whether a model is over-dispersed by inspecting the model summary. As a rule of thumb, if the response variable conforms to a true Poisson distribution, we expect the residual deviance to be approximately equal to the residual degrees of freedom. If the deviance is much greater than the degrees of freedom, this indicates over-dispersion. This is the case in our models.</p>
<p>To check the model assumptions in a GLM is not as straight forward as with a linear model. This is because classical residuals are not expected to behave in the same way for GLMs. We can use the DHARMa package in R for working with GLMs, which uses a simulation-based approach to compare the residuals from the actual model with the expectation if the model is behaving normally:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate residuals </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>simResids <span class="ot">&lt;-</span> DHARMa<span class="sc">::</span><span class="fu">simulateResiduals</span>(bryoModel1)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate plots to compare the model residuals to expectations</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(simResids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/model%20assumptions1-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>These plots show us that this model is not behaving as we would expect in terms of homogeneity of variance and distribution of residuals. A follow up to this would be to try alternatives to deal with over-dispersed count data in GLMs such as fit a quasi-Poisson GLM or a negative binomial GLM. Unfortunately we do not have time to continuou in this exercise.</p>
</section>
</section>
<section id="sec-q2" class="level2">
<h2 class="anchored" data-anchor-id="sec-q2">Question 2</h2>
<ul>
<li>Is the number of Briophites species affected by forest management type and the forest structural diversity?</li>
</ul>
<section id="fitting-a-poisson-glm-in-r-1" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-poisson-glm-in-r-1">Fitting a Poisson GLM in R</h3>
<p>Fitting a Poisson GLM in R is very similar to fitting an analysis of covariance (or linear model), except that now we need to use the glm function. To run a GLM, we need to provide one extra piece of information beyond that needed for a linear model: the family of model we want to use. In this case, we want a Poisson family.</p>
<p>We could start by only looking at how the forest structural diversity affects the number Bryophytes species that we have in a plot. You can do this by creating a GLM model which has <code>bryophitaNumObs</code> as response variable and <code>GiniDBH</code> as explanatory variable. For that you will use the function <code>glm</code> in R and use the <code>family = poisson</code>. You can see how to create and see this model here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>bryoModel1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(bryophitaNumObs <span class="sc">~</span> GiniDBH,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> poisson,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> observations)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bryoModel1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = bryophitaNumObs ~ GiniDBH, family = poisson, data = observations)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.4627     0.1388   3.333 0.000859 ***
GiniDBH       2.2797     0.4221   5.401 6.64e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 188.58  on 98  degrees of freedom
Residual deviance: 159.92  on 97  degrees of freedom
AIC: 424.2

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Here you can see that the coefficient table produced by a GLM is very similar to a linear model. The intercept tells us the estimated value of the response variable when the continuous explanatory variables (here just Gini index) have a value of 0. We then also have coefficients describing the slope of the relationship with our continuous explanatory variables. We can see here that the bryophita numbers appears to show a positive relationship with Gini index, which means that increasing structural diversity in trees diameter sizes has a positive relationship with the number of bryophita species in the plot.</p>
<p>We are also interested in understanding the relationship with of the number of observed Bryophytes species and forest management, we can now try to add this variable into the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>bryoModel2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(bryophitaNumObs <span class="sc">~</span> forestManagementType,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> poisson,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> observations)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bryoModel2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = bryophitaNumObs ~ forestManagementType, family = poisson, 
    data = observations)

Coefficients:
                                        Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)                               0.9651     0.1543   6.254 3.99e-10
forestManagementTypesimple clearcutting  -0.1335     0.1750  -0.763    0.445
forestManagementTypeunmanaged             0.7633     0.1821   4.192 2.76e-05
                                           
(Intercept)                             ***
forestManagementTypesimple clearcutting    
forestManagementTypeunmanaged           ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 188.58  on 98  degrees of freedom
Residual deviance: 141.54  on 96  degrees of freedom
AIC: 407.82

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>The intercept here tells us the estimated value of the response variable when the reference groups in our grouping (categorical) variables (here for retention clear-cutting). We then also have coefficients describing the slope of the relationship with our continuous explanatory variables, and coefficients giving the estimated difference in the response variable for non-reference groupings. We can see here that number of bryophites species appears to show a negative relationship with simple clearcutting, and appears to have a positive relationship with unmanaged and retention clear-cutting.</p>
<p>The type simple clearcutting it appears to be no significant, which only tell us about the&nbsp;pairwise differences between the levels. To test whether the categorical predictor, as a whole, is significant is equivalent to testing whether there is any heterogeneity in the means of the levels of the predictor. When there are no other predictors in the model, this is a classical&nbsp;<a href="http://en.wikipedia.org/wiki/Analysis_of_variance">ANOVA</a> problem.</p>
</section>
<section id="explanatory-power-of-the-model-1" class="level3">
<h3 class="anchored" data-anchor-id="explanatory-power-of-the-model-1">Explanatory Power of the model</h3>
<p>When we ran linear models, we used the coefficient of determination, or R<sup>2</sup>&nbsp;to assess how much of the variability in our response variable is explained by a given model. R<sup>2</sup>&nbsp;is based on the sums of squares of our model, and so cannot be calculated for GLMs. Instead, we can calculate the the deviance explained by our model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the null and residual deviance from the model</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>dev.null <span class="ot">&lt;-</span> bryoModel1<span class="sc">$</span>null.deviance</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>dev.resid <span class="ot">&lt;-</span> bryoModel1<span class="sc">$</span>deviance</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the deviance explained by the model</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>dev.explained <span class="ot">&lt;-</span> (dev.null <span class="sc">-</span> dev.resid)<span class="sc">/</span>dev.null</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Round to 3 decimal places</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>dev.explained <span class="ot">&lt;-</span> <span class="fu">round</span>(dev.explained, <span class="dv">3</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>dev.explained</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.152</code></pre>
</div>
</div>
<p>Variability in forest structure (Gini index) explain 15% of the variation in bryophita species richness in this study system. That is an ok explanatory power for a very simple model of a complex ecological system (many factors determine the species richness for bryophitas and we are attempting to explain everything with one variable).</p>
</section>
<section id="model-assumptions-1" class="level3">
<h3 class="anchored" data-anchor-id="model-assumptions-1">Model Assumptions</h3>
<p>For Poisson GLMs, there is one further assumption that we have not encountered before. If data follow a Poisson distribution, then the mean of the distribution is equal to the variance. Accordingly, a Poisson distribution is represented by just one parameter λ, which describes both the mean and the variance of the distribution.</p>
<p>Count data in ecology are often&nbsp;<strong><em>overdispersed</em></strong>, where the variance is greater than the mean. This violates the assumption of a Poisson GLM, and means that any statistics that we calculate from the model may be unreliable.</p>
<p>We can get an indication of whether a model is over-dispersed by inspecting the model summary. As a rule of thumb, if the response variable conforms to a true Poisson distribution, we expect the residual deviance to be approximately equal to the residual degrees of freedom. If the deviance is much greater than the degrees of freedom, this indicates over-dispersion. This is the case in our models.</p>
<p>To check the model assumptions in a GLM is not as straight forward as with a linear model. This is because classical residuals are not expected to behave in the same way for GLMs. We can use the DHARMa package in R for working with GLMs, which uses a simulation-based approach to compare the residuals from the actual model with the expectation if the model is behaving normally.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate residuals </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>simResids <span class="ot">&lt;-</span> DHARMa<span class="sc">::</span><span class="fu">simulateResiduals</span>(bryoModel1)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate plots to compare the model residuals to expectations</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(simResids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/model%20assumptions2%20-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>These plots show us that this model is not behaving as we would expect in terms of homogeneity of variance and distribution of residuals. A follow up to this would be to try alternatives to deal with over-dispersed count data in GLMs such as fit a quasi-Poisson GLM or a negative binomial GLM. Unfortunately we do not have to continuou in this exercise.</p>
</section>
</section>
<section id="sec-q3" class="level2">
<h2 class="anchored" data-anchor-id="sec-q3">Question 3</h2>
<ul>
<li>Does a more diverse forest in structure and composition have more bird species?</li>
</ul>
<section id="fitting-a-poisson-glm-in-r-2" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-poisson-glm-in-r-2">Fitting a Poisson GLM in R</h3>
<p>During your data exploration you should have selected your response variable: <code>bryophitaNumObs</code>. In this case since we are trying to understand forest structure and composition you should also select explanatory variables for that such as <code>GiniDBH</code> which indicates the forest structural diversity in diameter sizes, higher values indicate more structural heterogeneity and lower values indicate more homogeneous stands, or the <code>ShannonIndexTreeSpp</code> which assess the diversity of tree species in the plot.</p>
<p>We could start by only looking at how the forest structural diversity affects the number Bryophytes species that we have in a plot. You can do this by creating a GLM model which has <code>bryophitaNumObs</code> as response variable and <code>GiniDBH</code> as explanatory variable. For that you will use the function <code>glm</code>in R and use the <code>family = poisson</code>. You can see how to create and see this model here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>birdModel1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(birdNumObs <span class="sc">~</span> GiniDBH,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> poisson,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> observations)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(birdModel1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = birdNumObs ~ GiniDBH, family = poisson, data = observations)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  2.63827    0.05636  46.809   &lt;2e-16 ***
GiniDBH      0.42725    0.19030   2.245   0.0248 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 59.277  on 98  degrees of freedom
Residual deviance: 54.280  on 97  degrees of freedom
AIC: 511.57

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Here you can see that the coefficient table produced by a GLM is very similar to a linear model. The intercept tells us the estimated value of the response variable when the continuous explanatory variables (here just Gini index) has a value of 0. We then also have coefficients describing the slope of the relationship with our continuous explanatory variables. We can see here that the number of bird species appears to show a positive relationship with Gini index, which means that increasing structural diversity in trees diameter sizes has a positive relationship with the number of bird species in the plot.</p>
<p>We are also interested in understanding the relationship with the number of bird species and the trees species diversity, we can now try to add this variable into the model and see if it help us to understand things. You can do that by adding the variable <code>ShannonIndexTreeSpp</code> into the model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>birdModel2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(birdNumObs <span class="sc">~</span> GiniDBH <span class="sc">+</span> ShannonIndexTreeSpp,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> poisson,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> observations)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(birdModel2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = birdNumObs ~ GiniDBH + ShannonIndexTreeSpp, family = poisson, 
    data = observations)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)          2.63499    0.05665  46.513   &lt;2e-16 ***
GiniDBH              0.33323    0.21661   1.538    0.124    
ShannonIndexTreeSpp  0.06923    0.07444   0.930    0.352    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 59.277  on 98  degrees of freedom
Residual deviance: 53.419  on 96  degrees of freedom
AIC: 512.71

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Here we can see that the variable Shannon index also has a positive relationship with the number of bird species in the plot but its effect is much smaller. We can also observed that this variable it is not significant and that including this variable also made Gini index variable not significant. This does not mean that is wrong to add this variable, because we want to understand its effect, but keeping this variable in the model or not it depends on what you’re trying to do, and what “reality” is. Adding variables that are not needed will not help your model (particularly your estimates), but also might not matter much (e.g.&nbsp;predictions). However, removing variables that are real, even if they don’t meet significance, can create a useless model.</p>
<p>Variable selection is a long and complicated topic. some general rules of thumb include: (1) Include the variable if it is of interest, (2) Include the variable if you have some prior knowledge that it should be relevant. This can be misleading, because it’s a confirmation bias, but in most cases this makes sense. (3) If you want a model that can generalize to many cases, you should favor fewer variables.</p>
</section>
<section id="explanatory-power-of-the-model-2" class="level3">
<h3 class="anchored" data-anchor-id="explanatory-power-of-the-model-2">Explanatory Power of the model</h3>
<p>When we ran linear models, we used the coefficient of determination, or R<sup>2</sup>&nbsp;to assess how much of the variability in our response variable is explained by a given model. R<sup>2</sup>&nbsp;is based on the sums of squares of our model, and so cannot be calculated for GLMs. Instead, we can calculate the the deviance explained by our model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the null and residual deviance from the model</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>dev.null <span class="ot">&lt;-</span> birdModel1<span class="sc">$</span>null.deviance</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>dev.resid <span class="ot">&lt;-</span> birdModel1<span class="sc">$</span>deviance</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the deviance explained by the model</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>dev.explained <span class="ot">&lt;-</span> (dev.null <span class="sc">-</span> dev.resid)<span class="sc">/</span>dev.null</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Round to 3 decimal places</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>dev.explained <span class="ot">&lt;-</span> <span class="fu">round</span>(dev.explained, <span class="dv">3</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>dev.explained</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.084</code></pre>
</div>
</div>
<p>Variability in forest structure (Gini index) explain 8% of the variation in bird species richness in this study. That is an ok explanatory power for a very simple model of a complex ecological system (many factors determine the species richness for birds and we are attempting to explain everything with just one variable).</p>
</section>
<section id="model-assumptions-2" class="level3">
<h3 class="anchored" data-anchor-id="model-assumptions-2">Model Assumptions</h3>
<p>For Poisson GLMs, there is one further assumption that we have not encountered before. If data follow a Poisson distribution, then the mean of the distribution is equal to the variance. Accordingly, a Poisson distribution is represented by just one parameter λ, which describes both the mean and the variance of the distribution.</p>
<p>Count data in ecology are often&nbsp;<strong>overdispersed</strong>, where the variance is greater than the mean. This violates the assumption of a Poisson GLM, and means that any statistics that we calculate from the model may be unreliable.</p>
<p>We can get an indication of whether a model is over-dispersed by inspecting the model summary. As a rule of thumb, if the response variable conforms to a true Poisson distribution, we expect the residual deviance to be approximately equal to the residual degrees of freedom. If the deviance is much greater than the degrees of freedom, this indicates over-dispersion. This is the case in our models.</p>
<p>To check the model assumptions in a GLM is not as straight forward as with a linear model. This is because classical residuals are not expected to behave in the same way for GLMs. We can use the DHARMa package in R for working with GLMs, which uses a simulation-based approach to compare the residuals from the actual model with the expectation if the model is behaving normally:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate residuals </span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>simResids <span class="ot">&lt;-</span> DHARMa<span class="sc">::</span><span class="fu">simulateResiduals</span>(birdModel1)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate plots to compare the model residuals to expectations</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(simResids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/model%20assumptions3-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>These plots show us that this model is not behaving as we would expect in terms of homogeneity of variance and distribution of residuals. A follow up to this would be to try alternatives to deal with over-dispersed count data in GLMs such as fit a quasi-Poisson GLM or a negative binomial GLM. Unfortunately we do not have time to continuou in this exercise.</p>
</section>
</section>
<section id="sec-q4" class="level2">
<h2 class="anchored" data-anchor-id="sec-q4">Question 4</h2>
<ul>
<li>Is the number of bird species affected by forest management type and the forest structural diversity?</li>
</ul>
<section id="fitting-a-poisson-glm-in-r-3" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-poisson-glm-in-r-3">Fitting a Poisson GLM in R</h3>
<p>Fitting a Poisson GLM in R is very similar to fitting an analysis of covariance (or linear model), except that now we need to use the glm function. To run a GLM, we need to provide one extra piece of information beyond that needed for a linear model: the family of model we want to use. In this case, we want a Poisson family.</p>
<p>We could start by only looking at how the forest structural diversity affects the number Bryophytes species that we have in a plot. You can do this by creating a GLM model which has <code>birdNumObs</code> as response variable and <code>GiniDBH</code> as explanatory variable. For that you will use the function <code>glm</code> in R and use the <code>family = poisson</code>. You can see how to create and see this model here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>birdModel1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(birdNumObs <span class="sc">~</span> GiniDBH,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> poisson,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> observations)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(birdModel1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = birdNumObs ~ GiniDBH, family = poisson, data = observations)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  2.63827    0.05636  46.809   &lt;2e-16 ***
GiniDBH      0.42725    0.19030   2.245   0.0248 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 59.277  on 98  degrees of freedom
Residual deviance: 54.280  on 97  degrees of freedom
AIC: 511.57

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Here you can see that the coefficient table produced by a GLM is very similar to a linear model. The intercept tells us the estimated value of the response variable when the continuous explanatory variables (here just Gini index) have a value of 0. We then also have coefficients describing the slope of the relationship with our continuous explanatory variables. We can see here that the bird numbers appears to show a positive relationship with Gini index, which means that increasing structural diversity in trees diameter sizes has a positive relationship with the number of bird species in the plot.</p>
<p>We are also interested in understanding the relationship with of the number of observed bird species and forest management, we can now try to add this variable into the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>birdModel2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(birdNumObs <span class="sc">~</span> forestManagementType,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> poisson,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> observations)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(birdModel2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = birdNumObs ~ forestManagementType, family = poisson, 
    data = observations)

Coefficients:
                                        Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)                              2.83688    0.06052  46.873   &lt;2e-16
forestManagementTypesimple clearcutting -0.11744    0.06850  -1.714   0.0865
forestManagementTypeunmanaged           -0.06429    0.08338  -0.771   0.4407
                                           
(Intercept)                             ***
forestManagementTypesimple clearcutting .  
forestManagementTypeunmanaged              
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 59.277  on 98  degrees of freedom
Residual deviance: 56.205  on 96  degrees of freedom
AIC: 515.49

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>The intercept here tells us the estimated value of the response variable when the reference groups in our grouping (categorical) variables (here for retention clear-cutting). We then also have coefficients describing the slope of the relationship with our continuous explanatory variables, and coefficients giving the estimated difference in the response variable for non-reference groupings. We can see here that number of bird species appears to show a negative relationship with simple clearcutting, unmanaged and a positive relationship with retention clear-cutting.</p>
<p>The type simple clearcutting and unmanaged it appears to be no significant, which only tell us about the&nbsp;pairwise differences between the levels. To test whether the categorical predictor, as a whole, is significant is equivalent to testing whether there is any heterogeneity in the means of the levels of the predictor. When there are no other predictors in the model, this is a classical&nbsp;<a href="http://en.wikipedia.org/wiki/Analysis_of_variance">ANOVA</a> problem.</p>
</section>
<section id="explanatory-power-of-the-model-3" class="level3">
<h3 class="anchored" data-anchor-id="explanatory-power-of-the-model-3">Explanatory Power of the model</h3>
<p>When we ran linear models, we used the coefficient of determination, or R<sup>2</sup>&nbsp;to assess how much of the variability in our response variable is explained by a given model. R<sup>2</sup>&nbsp;is based on the sums of squares of our model, and so cannot be calculated for GLMs. Instead, we can calculate the the deviance explained by our model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the null and residual deviance from the model</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dev.null <span class="ot">&lt;-</span> birdModel1<span class="sc">$</span>null.deviance</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>dev.resid <span class="ot">&lt;-</span> birdModel1<span class="sc">$</span>deviance</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the deviance explained by the model</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>dev.explained <span class="ot">&lt;-</span> (dev.null <span class="sc">-</span> dev.resid)<span class="sc">/</span>dev.null</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Round to 3 decimal places</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>dev.explained <span class="ot">&lt;-</span> <span class="fu">round</span>(dev.explained, <span class="dv">3</span>)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>dev.explained</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.084</code></pre>
</div>
</div>
<p>Variability in forest structure (Gini index) explain 15% of the variation in bryophita species richness in this study system. That is an ok explanatory power for a very simple model of a complex ecological system (many factors determine the species richness for bryophitas and we are attempting to explain everything with one variable).</p>
</section>
<section id="model-assumptions-3" class="level3">
<h3 class="anchored" data-anchor-id="model-assumptions-3">Model Assumptions</h3>
<p>For Poisson GLMs, there is one further assumption that we have not encountered before. If data follow a Poisson distribution, then the mean of the distribution is equal to the variance. Accordingly, a Poisson distribution is represented by just one parameter λ, which describes both the mean and the variance of the distribution.</p>
<p>Count data in ecology are often&nbsp;<strong><em>overdispersed</em></strong>, where the variance is greater than the mean. This violates the assumption of a Poisson GLM, and means that any statistics that we calculate from the model may be unreliable.</p>
<p>We can get an indication of whether a model is over-dispersed by inspecting the model summary. As a rule of thumb, if the response variable conforms to a true Poisson distribution, we expect the residual deviance to be approximately equal to the residual degrees of freedom. If the deviance is much greater than the degrees of freedom, this indicates over-dispersion. This is the case in our models.</p>
<p>To check the model assumptions in a GLM is not as straight forward as with a linear model. This is because classical residuals are not expected to behave in the same way for GLMs. We can use the DHARMa package in R for working with GLMs, which uses a simulation-based approach to compare the residuals from the actual model with the expectation if the model is behaving normally.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate residuals </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>simResids <span class="ot">&lt;-</span> DHARMa<span class="sc">::</span><span class="fu">simulateResiduals</span>(birdModel1)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate plots to compare the model residuals to expectations</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(simResids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/model%20assumptions4%20-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>These plots show us that this model is not behaving as we would expect in terms of homogeneity of variance and distribution of residuals. A follow up to this would be to try alternatives to deal with over-dispersed count data in GLMs such as fit a quasi-Poisson GLM or a negative binomial GLM. Unfortunately we do not have to continuou in this exercise.</p>
</section>
</section>
<section id="sec-q5" class="level2">
<h2 class="anchored" data-anchor-id="sec-q5">Question 5</h2>
<ul>
<li>Is the presence of the Great spotted woodpecker affected by forest density?</li>
</ul>
<section id="fitting-a-brt-in-r" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-brt-in-r">Fitting a BRT in R</h3>
<p>In this case we want to assess the occurrence of certain species across the plots. In other words, we want to assess what is the probability of a certain species with biodiversity interest to be present in a plot based on the variables that describe the forest of that plot. In this case the response variable is <code>dendrocoposMajor</code> that represents if the Great spotted woodpecker has been observed in this plot or not.</p>
<p>Then you need to select some variables of interest, after you have explored the data you can decide which variables you want to use to fit this model. We are proposing to select the following variables:</p>
<ul>
<li><p><code>latitude</code> as proxy for plot location or/and climate</p></li>
<li><p><code>forestManagementType</code> to assess if different management types have different impact in the presence / absence of Parus major.</p></li>
<li><p><code>volAllha</code> that is the total volume in the plot, as a proxy of how dense the plot is. Higher volumes will mean that the forest is more dense.</p></li>
<li><p><code>GiniDBH</code> showing how homogeneous the plot is in trees diameters. A value closer to 1 will mean that indicate more structural heterogeneity, lower values indicate more homogeneous plots.</p></li>
<li><p><code>Birds_rich</code> are the species richness value calculated for all bird species species, higher value indicate higher species richness for birds.</p></li>
</ul>
<p>You can create a vector <code>selVar</code> in which you add the names of the selected variables. Then you only take those variables from the data that you will use to create the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select variables from the dataset for the model</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>selVar <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"dendrocoposMajor"</span>, <span class="st">"latitude"</span>,<span class="st">"forestManagementType"</span>,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>            <span class="st">"volAllha"</span>, <span class="st">"GiniDBH"</span>,  <span class="st">"ShannonIndexTreeSpp"</span>, <span class="st">"Birds_rich"</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the dataset to the selected variables</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>modelDataSel <span class="ot">&lt;-</span> observations[, <span class="fu">colnames</span>(observations) <span class="sc">%in%</span> selVar]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Unfortunately the amount of that we have in this dataset it is not enough to fit a BRT model for these variables. We are going to do an obviously wrong thing for the shake of being able to demonstrate how to fit a BRT model. In the next code you are going to repeat the same dataset multiple times:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>modelDataSel <span class="ot">&lt;-</span> <span class="fu">rbind</span>(modelDataSel, modelDataSel, modelDataSel, modelDataSel,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                      modelDataSel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now it is important to assess if the variables have the right categories. Variables should be type numeric or factor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelDataSel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    latitude     forestManagementType    volAllha          GiniDBH       
 Min.   :48.65   Length:495           Min.   :  1.681   Min.   :0.08209  
 1st Qu.:49.31   Class :character     1st Qu.:319.920   1st Qu.:0.13684  
 Median :49.40   Mode  :character     Median :434.729   Median :0.20358  
 Mean   :49.49                        Mean   :425.694   Mean   :0.25683  
 3rd Qu.:50.19                        3rd Qu.:558.355   3rd Qu.:0.37368  
 Max.   :50.34                        Max.   :777.882   Max.   :0.52852  
 ShannonIndexTreeSpp   Birds_rich     dendrocoposMajor
 Min.   :0.000       Min.   :0.1694   Min.   :0.0000  
 1st Qu.:0.060       1st Qu.:0.3995   1st Qu.:0.0000  
 Median :0.280       Median :0.4679   Median :1.0000  
 Mean   :0.392       Mean   :0.4698   Mean   :0.7071  
 3rd Qu.:0.680       3rd Qu.:0.5089   3rd Qu.:1.0000  
 Max.   :1.450       Max.   :0.8360   Max.   :1.0000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Two variables are character, we assign to factor instead:</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>modelDataSel<span class="sc">$</span>forestManagementType <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(modelDataSel<span class="sc">$</span>forestManagementType)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the next step you can see how you can run the model with the selected variables and model parameters. You have a description of the models parameters in the <a href="#sec-modelBRT">Section&nbsp;4.2</a> . In this example we are going to use the default parameters for the calibration, where learning rate = 0.01 and tree complexity = 1 and cross-validation = 10-fold. However, the bag fraction is changed from the default value, 0.75, to 0.5. As a family we used the Bernoulli family, because we are predicting presence/absence per plot. These data have 495 plots, comprising 350 presence records for the Great spotted woodpecker. You can check these numbers by doing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(modelDataSel<span class="sc">$</span>dendrocoposMajor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
145 350 </code></pre>
</div>
</div>
<p>As a first guess you could decide there are enough data to model interactions of reasonable complexity, and a lr of about 0.01 could be a reasonable starting point. You can use the model creation function that steps forward and identifies the optimal number of trees (nt) by doing this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>family <span class="ot">&lt;-</span> <span class="st">"bernoulli"</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>    tc <span class="ot">=</span> <span class="dv">1</span>    <span class="co"># tree complexity</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    lr <span class="ot">=</span> <span class="fl">0.01</span> <span class="co"># learning rate-shrinkage </span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    bag <span class="ot">=</span> <span class="fl">0.5</span> <span class="co"># bag fraction</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    modelBRT <span class="ot">&lt;-</span> dismo<span class="sc">::</span><span class="fu">gbm.step</span>(<span class="at">data =</span> modelDataSel,</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>                          <span class="co">#indices of predictor variables in data</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">gbm.x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, </span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>                          <span class="co">#index of response variable in data:</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>                          <span class="at">gbm.y =</span> <span class="dv">7</span>,  </span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family =</span> family,</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>                          <span class="at">tree.complexity =</span> tc,</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>                          <span class="at">learning.rate =</span> lr,</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>                          <span class="at">bag.fraction =</span> bag)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/BRTmodel-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Running a model such as that described above writes progress reports to the screen, makes a graph, and returns an object containing a number of components. The R console results reports a brief model summary all the values are also retained in the model object.</p>
<p>The model is built with the default 10-fold cross-validation (CV). In the plotted graph the solid black curve is the mean, and the dotted curves 1 standard error, for the changes in predictive deviance (i.e., as measured on the excluded folds of the CV). The red line shows the minimum of the mean, and the green line the number of trees at which that occurs. The final model that is returned in the model object is built on the full data set, using the number of trees identified as optimal.</p>
<p>Ideally, you should invest time in modifying the parameters and finr the parameters that provide the models with the minimum deviance resulting from the best combination of bag, tree complexity and learning rate values. For the shake of limited timing, we will only test here the default values.</p>
</section>
<section id="model-behaviour" class="level3">
<h3 class="anchored" data-anchor-id="model-behaviour">Model behaviour</h3>
<p>You can summarized the model parameters used and the cross validation statistics from the fitted model by doing this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We make a table with the summary statistics  </span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a> results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Model parameters</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="at">Tree.Complexity =</span> modelBRT<span class="sc">$</span>gbm.call<span class="sc">$</span>tree.complexity, </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="at">Learning.Rate =</span> modelBRT<span class="sc">$</span>gbm.call<span class="sc">$</span>learning.rate, </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Bag.Fraction =</span> modelBRT<span class="sc">$</span>gbm.call<span class="sc">$</span>bag.fraction,</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Interaction.depth =</span> modelBRT<span class="sc">$</span>interaction.depth,</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Shrinkage =</span> modelBRT<span class="sc">$</span>shrinkage,</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">N.trees =</span> modelBRT<span class="sc">$</span>n.trees,</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Cross validation statistics </span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="do">## mean total deviance</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a><span class="at">Deviance =</span> modelBRT<span class="sc">$</span>self.statistics<span class="sc">$</span>mean.resid, <span class="co"># mean residual deviance </span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a><span class="at">AUC =</span> modelBRT<span class="sc">$</span>self.statistics<span class="sc">$</span>discrimination, <span class="co"># training data AUC score</span></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a><span class="at">Corr =</span> modelBRT<span class="sc">$</span>self.statistics<span class="sc">$</span>correlation,   <span class="co"># training data correlation</span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a><span class="do">## Cross Validation statistics</span></span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a><span class="co"># We calculate each statistic within each fold (at the identified optimal number</span></span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a><span class="co"># of trees that is calculated on the mean change in predictive deviance over all folds), </span></span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a><span class="co">#then present here the mean and standard error of those fold-based statistics.</span></span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a><span class="at">devianceCV =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>deviance.mean,  <span class="co"># estimated cv deviance </span></span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a><span class="at">devianceCVse =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>deviance.se,  <span class="co"># estimated cv deviance se</span></span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb42-30"><a href="#cb42-30" aria-hidden="true" tabindex="-1"></a><span class="at">CorrCV =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>correlation.mean,  <span class="co">#cv correlation</span></span>
<span id="cb42-31"><a href="#cb42-31" aria-hidden="true" tabindex="-1"></a><span class="at">CorrCVse =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>correlation.se,  <span class="co">#cv correlation se</span></span>
<span id="cb42-32"><a href="#cb42-32" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb42-33"><a href="#cb42-33" aria-hidden="true" tabindex="-1"></a><span class="at">AUCcv =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>discrimination.mean, <span class="co"># cv AUC score</span></span>
<span id="cb42-34"><a href="#cb42-34" aria-hidden="true" tabindex="-1"></a><span class="at">AUCcvSE =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>discrimination.se)  <span class="co"># cv AUC score se</span></span>
<span id="cb42-35"><a href="#cb42-35" aria-hidden="true" tabindex="-1"></a>                </span>
<span id="cb42-36"><a href="#cb42-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb42-37"><a href="#cb42-37" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">t</span>(results))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          [,1]
Tree.Complexity   1.000000e+00
Learning.Rate     1.000000e-02
Bag.Fraction      5.000000e-01
Interaction.depth 1.000000e+00
Shrinkage         1.000000e-02
N.trees           1.000000e+04
Deviance          1.761963e-01
AUC               1.000000e+00
Corr              9.841888e-01
devianceCV        2.110045e-01
devianceCVse      5.974782e-03
CorrCV            9.739618e-01
CorrCVse          2.774806e-03
AUCcv             1.000000e+00
AUCcvSE           0.000000e+00</code></pre>
</div>
</div>
</section>
<section id="model-output-analysis" class="level3">
<h3 class="anchored" data-anchor-id="model-output-analysis">Model output analysis</h3>
<p>We can look at the relative contribution of each of the predictor variables. The measures are based on the number of time the variable is selected for splitting, weighted by the improvement of the model as a result of each split averaged across all trees. The relative contribution of each of the variables is scaled so the sum is 100%, with higher numbers indicating stronger influence in the response.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables contribution </span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>modelBRT<span class="sc">$</span>contributions </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                      var   rel.inf
latitude                         latitude 24.016889
volAllha                         volAllha 22.442142
Birds_rich                     Birds_rich 21.181480
GiniDBH                           GiniDBH 17.605417
ShannonIndexTreeSpp   ShannonIndexTreeSpp  9.265475
forestManagementType forestManagementType  5.488597</code></pre>
</div>
</div>
<p>Here we can see that the two variables with the highest influence in the response are <code>latitude</code>, and <code>volAllhsa</code>.</p>
<p>Now we can evaluate the model behavior via partial dependence plots, showing the effect of each of the variables on the response by accounting for the average effects of all other predictors in the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>    dismo<span class="sc">::</span><span class="fu">gbm.plot</span>(modelBRT, <span class="at">n.plots =</span> <span class="dv">6</span>,</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">plot.layout =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>), <span class="at">write.title =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/marginallEffects-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this partial dependence plots the predictions are on the scale of f(x). In this case, for the Bernoulli loss the returned value is on the log odds scale. You can see how this plot will look by plotting with the function from the package <code>gbm</code> and using the type “response”. Since we are interesting in finding out if the forest density has an impact in the presence of the Great spotted woodpecker we can have a look to the plot density variable <code>volAllha</code> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>gbm<span class="sc">::</span><span class="fu">plot.gbm</span>(modelBRT, <span class="at">i.var =</span> <span class="dv">3</span>, <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">ylab =</span> <span class="st">"Probability of finding a Great spotted woodpecker "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/response-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It seems that there is an increase in probability of finding a Great spotted woodpecker with higher forest densities, but the trend it is not very clear. We could also analyse the interaction effects, of density and for example overall bird richness. The model predictions can be obtained for each pair of predictor variables, setting all other predictors to their means.</p>
<p>To plot this pairwise interactions we have to do:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>dismo<span class="sc">::</span><span class="fu">gbm.perspec</span>(modelBRT, <span class="dv">3</span>, <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/pairwise%20int-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here we can see that both increasing bird diversity and forest density provides the highest probabilities for finding the Great spotted woodpecker.</p>
</section>
</section>
<section id="sec-q6" class="level2">
<h2 class="anchored" data-anchor-id="sec-q6">Question 6</h2>
<ul>
<li>Is the presence of the Great spotted woodpecker affected by forest diversity?</li>
</ul>
<section id="fitting-a-brt-in-r-1" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-brt-in-r-1">Fitting a BRT in R</h3>
<p>In this case we want to assess the occurrence of certain species across the plots. In other words, we want to assess what is the probability of a certain species with biodiversity interest to be present in a plot based on the variables that describe the forest of that plot. In this case the response variable is <code>dendrocoposMajor</code> that represents if the Great spotted woodpecker has been observed in this plot or not.</p>
<p>Then you need to select some variables of interest, after you have explored the data you can decide which variables you want to use to fit this model. We are proposing to select the following variables:</p>
<ul>
<li><p><code>latitude</code> as proxy for plot location or/and climate</p></li>
<li><p><code>forestManagementType</code> to assess if different management types have different impact in the presence / absence of Parus major.</p></li>
<li><p><code>volAllha</code> that is the total volume in the plot, as a proxy of how dense the plot is. Higher volumes will mean that the forest is more dense.</p></li>
<li><p><code>GiniDBH</code> showing how homogeneous the plot is in trees diameters. A value closer to 1 will mean that indicate more structural heterogeneity, lower values indicate more homogeneous plots.</p></li>
<li><p><code>Birds_rich</code> are the species richness value calculated for all bird species species, higher value indicate higher species richness for birds.</p></li>
</ul>
<p>You can create a vector <code>selVar</code> in which you add the names of the selected variables. Then you only take those variables from the data that you will use to create the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select variables from the dataset for the model</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>selVar <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"dendrocoposMajor"</span>, <span class="st">"latitude"</span>,<span class="st">"forestManagementType"</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>            <span class="st">"volAllha"</span>,<span class="st">"GiniDBH"</span>,  <span class="st">"ShannonIndexTreeSpp"</span>, <span class="st">"Birds_rich"</span>)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the dataset to the selected variables</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>modelDataSel <span class="ot">&lt;-</span> observations[, <span class="fu">colnames</span>(observations) <span class="sc">%in%</span> selVar]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Unfortunately the amount of that we have in this dataset it is not enough to fit a BRT model for these variables. We are going to do an obviously wrong thing for the shake of being able to demonstrate how to fit a BRT model. In the next code you are going to repeat the same dataset multiple times:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>modelDataSel <span class="ot">&lt;-</span> <span class="fu">rbind</span>(modelDataSel, modelDataSel, modelDataSel, modelDataSel,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>                      modelDataSel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now it is important to assess if the variables have the right categories. Variables should be type numeric or factor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelDataSel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    latitude     forestManagementType    volAllha          GiniDBH       
 Min.   :48.65   Length:495           Min.   :  1.681   Min.   :0.08209  
 1st Qu.:49.31   Class :character     1st Qu.:319.920   1st Qu.:0.13684  
 Median :49.40   Mode  :character     Median :434.729   Median :0.20358  
 Mean   :49.49                        Mean   :425.694   Mean   :0.25683  
 3rd Qu.:50.19                        3rd Qu.:558.355   3rd Qu.:0.37368  
 Max.   :50.34                        Max.   :777.882   Max.   :0.52852  
 ShannonIndexTreeSpp   Birds_rich     dendrocoposMajor
 Min.   :0.000       Min.   :0.1694   Min.   :0.0000  
 1st Qu.:0.060       1st Qu.:0.3995   1st Qu.:0.0000  
 Median :0.280       Median :0.4679   Median :1.0000  
 Mean   :0.392       Mean   :0.4698   Mean   :0.7071  
 3rd Qu.:0.680       3rd Qu.:0.5089   3rd Qu.:1.0000  
 Max.   :1.450       Max.   :0.8360   Max.   :1.0000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Two variables are character, we assign to factor instead:</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>modelDataSel<span class="sc">$</span>forestManagementType <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(modelDataSel<span class="sc">$</span>forestManagementType)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the next step you can see how you can run the model with the selected variables and model parameters. You have a description of the models parameters in the <a href="#sec-modelBRT">Section&nbsp;4.2</a> . In this example we are going to use the default parameters for the calibration, where learning rate = 0.01 and tree complexity = 1 and cross-validation = 10-fold. However, the bag fraction is changed from the default value, 0.75, to 0.5. As a family we used the Bernoulli family, because we are predicting presence/absence per plot. These data have 495 plots, comprising 350 presence records for the Great spotted woodpecker. You can check these numbers by doing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(modelDataSel<span class="sc">$</span>dendrocoposMajor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
145 350 </code></pre>
</div>
</div>
<p>As a first guess you could decide there are enough data to model interactions of reasonable complexity, and a lr of about 0.01 could be a reasonable starting point. You can use the model creation function that steps forward and identifies the optimal number of trees (nt) by doing this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>family <span class="ot">&lt;-</span> <span class="st">"bernoulli"</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>    tc <span class="ot">=</span> <span class="dv">1</span>    <span class="co"># tree complexity</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>    lr <span class="ot">=</span> <span class="fl">0.01</span> <span class="co"># learning rate-shrinkage </span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    bag <span class="ot">=</span> <span class="fl">0.5</span> <span class="co"># bag fraction</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>    modelBRT <span class="ot">&lt;-</span> dismo<span class="sc">::</span><span class="fu">gbm.step</span>(<span class="at">data =</span> modelDataSel,</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>                          <span class="co">#indices of predictor variables in data</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">gbm.x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, </span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>                          <span class="co">#index of response variable in data:</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>                          <span class="at">gbm.y =</span> <span class="dv">7</span>,  </span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family =</span> family,</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>                          <span class="at">tree.complexity =</span> tc,</span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>                          <span class="at">learning.rate =</span> lr,</span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>                          <span class="at">bag.fraction =</span> bag)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/BRTmodel6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Running a model such as that described above writes progress reports to the screen, makes a graph, and returns an object containing a number of components. The R console results reports a brief model summary all the values are also retained in the model object.</p>
<p>The model is built with the default 10-fold cross-validation (CV). In the plotted graph the solid black curve is the mean, and the dotted curves 1 standard error, for the changes in predictive deviance (i.e., as measured on the excluded folds of the CV). The red line shows the minimum of the mean, and the green line the number of trees at which that occurs. The final model that is returned in the model object is built on the full data set, using the number of trees identified as optimal.</p>
<p>Ideally, you should invest time in modifying the parameters and finr the parameters that provide the models with the minimum deviance resulting from the best combination of bag, tree complexity and learning rate values. For the shake of limited timing, we will only test here the default values.</p>
</section>
<section id="model-behaviour-1" class="level3">
<h3 class="anchored" data-anchor-id="model-behaviour-1">Model behaviour</h3>
<p>You can summarized the model parameters used and the cross validation statistics from the fitted model by doing this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We make a table with the summary statistics  </span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a> results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Model parameters</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="at">Tree.Complexity =</span> modelBRT<span class="sc">$</span>gbm.call<span class="sc">$</span>tree.complexity, </span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="at">Learning.Rate =</span> modelBRT<span class="sc">$</span>gbm.call<span class="sc">$</span>learning.rate, </span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Bag.Fraction =</span> modelBRT<span class="sc">$</span>gbm.call<span class="sc">$</span>bag.fraction,</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Interaction.depth =</span> modelBRT<span class="sc">$</span>interaction.depth,</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Shrinkage =</span> modelBRT<span class="sc">$</span>shrinkage,</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">N.trees =</span> modelBRT<span class="sc">$</span>n.trees,</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Cross validation statistics </span></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a><span class="do">## mean total deviance</span></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a><span class="at">Deviance =</span> modelBRT<span class="sc">$</span>self.statistics<span class="sc">$</span>mean.resid, <span class="co"># mean residual deviance </span></span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a><span class="at">AUC =</span> modelBRT<span class="sc">$</span>self.statistics<span class="sc">$</span>discrimination, <span class="co"># training data AUC score</span></span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a><span class="at">Corr =</span> modelBRT<span class="sc">$</span>self.statistics<span class="sc">$</span>correlation,   <span class="co"># training data correlation</span></span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a><span class="do">## Cross Validation statistics</span></span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a><span class="co"># We calculate each statistic within each fold (at the identified optimal number</span></span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a><span class="co"># of trees that is calculated on the mean change in predictive deviance over all folds), </span></span>
<span id="cb57-25"><a href="#cb57-25" aria-hidden="true" tabindex="-1"></a><span class="co">#then present here the mean and standard error of those fold-based statistics.</span></span>
<span id="cb57-26"><a href="#cb57-26" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb57-27"><a href="#cb57-27" aria-hidden="true" tabindex="-1"></a><span class="at">devianceCV =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>deviance.mean,  <span class="co"># estimated cv deviance </span></span>
<span id="cb57-28"><a href="#cb57-28" aria-hidden="true" tabindex="-1"></a><span class="at">devianceCVse =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>deviance.se,  <span class="co"># estimated cv deviance se</span></span>
<span id="cb57-29"><a href="#cb57-29" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb57-30"><a href="#cb57-30" aria-hidden="true" tabindex="-1"></a><span class="at">CorrCV =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>correlation.mean,  <span class="co">#cv correlation</span></span>
<span id="cb57-31"><a href="#cb57-31" aria-hidden="true" tabindex="-1"></a><span class="at">CorrCVse =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>correlation.se,  <span class="co">#cv correlation se</span></span>
<span id="cb57-32"><a href="#cb57-32" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb57-33"><a href="#cb57-33" aria-hidden="true" tabindex="-1"></a><span class="at">AUCcv =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>discrimination.mean, <span class="co"># cv AUC score</span></span>
<span id="cb57-34"><a href="#cb57-34" aria-hidden="true" tabindex="-1"></a><span class="at">AUCcvSE =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>discrimination.se)  <span class="co"># cv AUC score se</span></span>
<span id="cb57-35"><a href="#cb57-35" aria-hidden="true" tabindex="-1"></a>                </span>
<span id="cb57-36"><a href="#cb57-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb57-37"><a href="#cb57-37" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">t</span>(results))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          [,1]
Tree.Complexity   1.000000e+00
Learning.Rate     1.000000e-02
Bag.Fraction      5.000000e-01
Interaction.depth 1.000000e+00
Shrinkage         1.000000e-02
N.trees           1.000000e+04
Deviance          1.768564e-01
AUC               1.000000e+00
Corr              9.834254e-01
devianceCV        2.085052e-01
devianceCVse      7.644080e-03
CorrCV            9.758411e-01
CorrCVse          2.850691e-03
AUCcv             1.000000e+00
AUCcvSE           0.000000e+00</code></pre>
</div>
</div>
</section>
<section id="model-output-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="model-output-analysis-1">Model output analysis</h3>
<p>We can look at the relative contribution of each of the predictor variables. The measures are based on the number of time the variable is selected for splitting, weighted by the improvement of the model as a result of each split averaged across all trees. The relative contribution of each of the variables is scaled so the sum is 100%, with higher numbers indicating stronger influence in the response.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables contribution </span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>modelBRT<span class="sc">$</span>contributions </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                      var   rel.inf
latitude                         latitude 24.344661
volAllha                         volAllha 21.900588
Birds_rich                     Birds_rich 21.163539
GiniDBH                           GiniDBH 18.013838
ShannonIndexTreeSpp   ShannonIndexTreeSpp  9.359293
forestManagementType forestManagementType  5.218082</code></pre>
</div>
</div>
<p>Here we can see that the two variables with the highest influence in the response are <code>latitude</code>, and <code>volAllhsa</code>.</p>
<p>Now we can evaluate the model behavior via partial dependence plots, showing the effect of each of the variables on the response by accounting for the average effects of all other predictors in the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>    dismo<span class="sc">::</span><span class="fu">gbm.plot</span>(modelBRT, <span class="at">n.plots =</span> <span class="dv">6</span>,</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">plot.layout =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>), <span class="at">write.title =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/marginallEffects6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this partial dependence plots the predictions are on the scale of f(x). In this case, for the Bernoulli loss the returned value is on the log odds scale. You can see how this plot will look by plotting with the function from the package <code>gbm</code> and using the type “response”. Since we are interesting in finding out if the forest diversity has an impact in the presence of the Great spotted woodpecker we can have a look to the plot density variable <code>volAllha</code> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>gbm<span class="sc">::</span><span class="fu">plot.gbm</span>(modelBRT, <span class="at">i.var =</span> <span class="dv">5</span>, <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">ylab =</span> <span class="st">"Probability of finding a Great spotted woodpecker "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/response6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It seems that there is an increase in probability of finding a Great spotted woodpecker with higher forest densities, but the trend it is not very clear. We could also analyse the interaction effects, of forest diversity and for example forest density. The model predictions can be obtained for each pair of predictor variables, setting all other predictors to their means.</p>
<p>To plot this pairwise interactions we have to do:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>dismo<span class="sc">::</span><span class="fu">gbm.perspec</span>(modelBRT, <span class="dv">3</span>, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/pairwise%20int6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here we can not see a very clear combined behavior between forest diversity and forest structural diversity in respect to the probabilities for finding the Great spotted woodpecker.</p>
</section>
</section>
<section id="sec-q7" class="level2">
<h2 class="anchored" data-anchor-id="sec-q7">Question 7</h2>
<ul>
<li>Is the presence of the Eurasian treecreeper affected by forest density?</li>
</ul>
<section id="fitting-a-brt-in-r-2" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-brt-in-r-2">Fitting a BRT in R</h3>
<p>In this case we want to assess the occurrence of certain species across the plots. In other words, we want to assess what is the probability of a certain species with biodiversity interest to be present in a plot based on the variables that describe the forest of that plot. In this case the response variable is <code>phoenicurus</code> that represents if the Great spotted woodpecker has been observed in this plot or not.</p>
<p>Then you need to select some variables of interest, after you have explored the data you can decide which variables you want to use to fit this model. We are proposing to select the following variables:</p>
<ul>
<li><p><code>latitude</code> as proxy for plot location or/and climate</p></li>
<li><p><code>forestManagementType</code> to assess if different management types have different impact in the presence / absence of Parus major.</p></li>
<li><p><code>volAllha</code> that is the total volume in the plot, as a proxy of how dense the plot is. Higher volumes will mean that the forest is more dense.</p></li>
<li><p><code>GiniDBH</code> showing how homogeneous the plot is in trees diameters. A value closer to 1 will mean that indicate more structural heterogeneity, lower values indicate more homogeneous plots.</p></li>
</ul>
<p>You can create a vector <code>selVar</code> in which you add the names of the selected variables. Then you only take those variables from the data that you will use to create the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select variables from the dataset for the model</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>selVar <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"certhia"</span>, <span class="st">"latitude"</span>, <span class="st">"forestManagementType"</span>,</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>            <span class="st">"volAllha"</span>, <span class="st">"GiniDBH"</span>,  <span class="st">"ShannonIndexTreeSpp"</span>, </span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Birds_rich"</span>)</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the dataset to the selected variables</span></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>modelDataSel <span class="ot">&lt;-</span> observations[, <span class="fu">colnames</span>(observations) <span class="sc">%in%</span> selVar]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Unfortunately the amount of that we have in this dataset it is not enough to fit a BRT model for these variables. We are going to do an obviously wrong thing for the shake of being able to demonstrate how to fit a BRT model. In the next code you are going to repeat the same dataset multiple times:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>modelDataSel <span class="ot">&lt;-</span> <span class="fu">rbind</span>(modelDataSel, modelDataSel, modelDataSel, modelDataSel,</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>                      modelDataSel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now it is important to assess if the variables have the right categories. Variables should be type numeric or factor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelDataSel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    latitude     forestManagementType    volAllha          GiniDBH       
 Min.   :48.65   Length:495           Min.   :  1.681   Min.   :0.08209  
 1st Qu.:49.31   Class :character     1st Qu.:319.920   1st Qu.:0.13684  
 Median :49.40   Mode  :character     Median :434.729   Median :0.20358  
 Mean   :49.49                        Mean   :425.694   Mean   :0.25683  
 3rd Qu.:50.19                        3rd Qu.:558.355   3rd Qu.:0.37368  
 Max.   :50.34                        Max.   :777.882   Max.   :0.52852  
 ShannonIndexTreeSpp   Birds_rich        certhia      
 Min.   :0.000       Min.   :0.1694   Min.   :0.0000  
 1st Qu.:0.060       1st Qu.:0.3995   1st Qu.:0.0000  
 Median :0.280       Median :0.4679   Median :1.0000  
 Mean   :0.392       Mean   :0.4698   Mean   :0.5859  
 3rd Qu.:0.680       3rd Qu.:0.5089   3rd Qu.:1.0000  
 Max.   :1.450       Max.   :0.8360   Max.   :1.0000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Two variables are character, we assign to factor instead:</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>modelDataSel<span class="sc">$</span>forestManagementType <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(modelDataSel<span class="sc">$</span>forestManagementType)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the next step you can see how you can run the model with the selected variables and model parameters. You have a description of the models parameters in the <a href="#sec-modelBRT">Section&nbsp;4.2</a> . In this example we are going to use the default parameters for the calibration, where learning rate = 0.01 and tree complexity = 1 and cross-validation = 10-fold. However, the bag fraction is changed from the default value, 0.75, to 0.5. As a family we used the Bernoulli family, because we are predicting presence/absence per plot. These data have 495 plots, comprising 290 presence records for the Eurasian treecreeper. You can check these numbers by doing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(modelDataSel<span class="sc">$</span>certhia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
205 290 </code></pre>
</div>
</div>
<p>As a first guess you could decide there are enough data to model interactions of reasonable complexity, and a lr of about 0.01 could be a reasonable starting point. You can use the model creation function that steps forward and identifies the optimal number of trees (nt) by doing this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>family <span class="ot">&lt;-</span> <span class="st">"bernoulli"</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>    tc <span class="ot">=</span> <span class="dv">1</span>    <span class="co"># tree complexity</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>    lr <span class="ot">=</span> <span class="fl">0.01</span> <span class="co"># learning rate-shrinkage </span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>    bag <span class="ot">=</span> <span class="fl">0.5</span> <span class="co"># bag fraction</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>    modelBRT <span class="ot">&lt;-</span> dismo<span class="sc">::</span><span class="fu">gbm.step</span>(<span class="at">data =</span> modelDataSel,</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>                          <span class="co">#indices of predictor variables in data</span></span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">gbm.x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, </span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>                          <span class="co">#index of response variable in data:</span></span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>                          <span class="at">gbm.y =</span> <span class="dv">7</span>,  </span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family =</span> family,</span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a>                          <span class="at">tree.complexity =</span> tc,</span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a>                          <span class="at">learning.rate =</span> lr,</span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a>                          <span class="at">bag.fraction =</span> bag)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/BRTmodel7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Running a model such as that described above writes progress reports to the screen, makes a graph, and returns an object containing a number of components. The R console results reports a brief model summary all the values are also retained in the model object.</p>
<p>The model is built with the default 10-fold cross-validation (CV). In the plotted graph the solid black curve is the mean, and the dotted curves 1 standard error, for the changes in predictive deviance (i.e., as measured on the excluded folds of the CV). The red line shows the minimum of the mean, and the green line the number of trees at which that occurs. The final model that is returned in the model object is built on the full data set, using the number of trees identified as optimal.</p>
<p>Ideally, you should invest time in modifying the parameters and finr the parameters that provide the models with the minimum deviance resulting from the best combination of bag, tree complexity and learning rate values. For the shake of limited timing, we will only test here the default values.</p>
</section>
<section id="model-behaviour-2" class="level3">
<h3 class="anchored" data-anchor-id="model-behaviour-2">Model behaviour</h3>
<p>You can summarized the model parameters used and the cross validation statistics from the fitted model by doing this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We make a table with the summary statistics  </span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a> results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Model parameters</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a><span class="at">Tree.Complexity =</span> modelBRT<span class="sc">$</span>gbm.call<span class="sc">$</span>tree.complexity, </span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="at">Learning.Rate =</span> modelBRT<span class="sc">$</span>gbm.call<span class="sc">$</span>learning.rate, </span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Bag.Fraction =</span> modelBRT<span class="sc">$</span>gbm.call<span class="sc">$</span>bag.fraction,</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Interaction.depth =</span> modelBRT<span class="sc">$</span>interaction.depth,</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Shrinkage =</span> modelBRT<span class="sc">$</span>shrinkage,</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">N.trees =</span> modelBRT<span class="sc">$</span>n.trees,</span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Cross validation statistics </span></span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a><span class="do">## mean total deviance</span></span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a><span class="at">Deviance =</span> modelBRT<span class="sc">$</span>self.statistics<span class="sc">$</span>mean.resid, <span class="co"># mean residual deviance </span></span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a><span class="at">AUC =</span> modelBRT<span class="sc">$</span>self.statistics<span class="sc">$</span>discrimination, <span class="co"># training data AUC score</span></span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-19"><a href="#cb72-19" aria-hidden="true" tabindex="-1"></a><span class="at">Corr =</span> modelBRT<span class="sc">$</span>self.statistics<span class="sc">$</span>correlation,   <span class="co"># training data correlation</span></span>
<span id="cb72-20"><a href="#cb72-20" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb72-21"><a href="#cb72-21" aria-hidden="true" tabindex="-1"></a><span class="do">## Cross Validation statistics</span></span>
<span id="cb72-22"><a href="#cb72-22" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb72-23"><a href="#cb72-23" aria-hidden="true" tabindex="-1"></a><span class="co"># We calculate each statistic within each fold (at the identified optimal number</span></span>
<span id="cb72-24"><a href="#cb72-24" aria-hidden="true" tabindex="-1"></a><span class="co"># of trees that is calculated on the mean change in predictive deviance over all folds), </span></span>
<span id="cb72-25"><a href="#cb72-25" aria-hidden="true" tabindex="-1"></a><span class="co">#then present here the mean and standard error of those fold-based statistics.</span></span>
<span id="cb72-26"><a href="#cb72-26" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb72-27"><a href="#cb72-27" aria-hidden="true" tabindex="-1"></a><span class="at">devianceCV =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>deviance.mean,  <span class="co"># estimated cv deviance </span></span>
<span id="cb72-28"><a href="#cb72-28" aria-hidden="true" tabindex="-1"></a><span class="at">devianceCVse =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>deviance.se,  <span class="co"># estimated cv deviance se</span></span>
<span id="cb72-29"><a href="#cb72-29" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb72-30"><a href="#cb72-30" aria-hidden="true" tabindex="-1"></a><span class="at">CorrCV =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>correlation.mean,  <span class="co">#cv correlation</span></span>
<span id="cb72-31"><a href="#cb72-31" aria-hidden="true" tabindex="-1"></a><span class="at">CorrCVse =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>correlation.se,  <span class="co">#cv correlation se</span></span>
<span id="cb72-32"><a href="#cb72-32" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb72-33"><a href="#cb72-33" aria-hidden="true" tabindex="-1"></a><span class="at">AUCcv =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>discrimination.mean, <span class="co"># cv AUC score</span></span>
<span id="cb72-34"><a href="#cb72-34" aria-hidden="true" tabindex="-1"></a><span class="at">AUCcvSE =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>discrimination.se)  <span class="co"># cv AUC score se</span></span>
<span id="cb72-35"><a href="#cb72-35" aria-hidden="true" tabindex="-1"></a>                </span>
<span id="cb72-36"><a href="#cb72-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb72-37"><a href="#cb72-37" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">t</span>(results))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          [,1]
Tree.Complexity   1.000000e+00
Learning.Rate     1.000000e-02
Bag.Fraction      5.000000e-01
Interaction.depth 1.000000e+00
Shrinkage         1.000000e-02
N.trees           1.000000e+04
Deviance          2.755818e-01
AUC               1.000000e+00
Corr              9.720257e-01
devianceCV        3.246165e-01
devianceCVse      1.181460e-02
CorrCV            9.572421e-01
CorrCVse          3.956554e-03
AUCcv             1.000000e+00
AUCcvSE           0.000000e+00</code></pre>
</div>
</div>
</section>
<section id="model-output-analysis-2" class="level3">
<h3 class="anchored" data-anchor-id="model-output-analysis-2">Model output analysis</h3>
<p>We can look at the relative contribution of each of the predictor variables. The measures are based on the number of time the variable is selected for splitting, weighted by the improvement of the model as a result of each split averaged across all trees. The relative contribution of each of the variables is scaled so the sum is 100%, with higher numbers indicating stronger influence in the response.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables contribution </span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>modelBRT<span class="sc">$</span>contributions </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                      var    rel.inf
GiniDBH                           GiniDBH 26.6822654
volAllha                         volAllha 20.6813111
latitude                         latitude 19.9252679
Birds_rich                     Birds_rich 17.1233143
ShannonIndexTreeSpp   ShannonIndexTreeSpp 15.3442631
forestManagementType forestManagementType  0.2435782</code></pre>
</div>
</div>
<p>Here we can see that the two variables with the highest influence in the response are <code>GiniDBH</code> and <code>volAllhsa</code>.</p>
<p>Now we can evaluate the model behavior via partial dependence plots, showing the effect of each of the variables on the response by accounting for the average effects of all other predictors in the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>    dismo<span class="sc">::</span><span class="fu">gbm.plot</span>(modelBRT, <span class="at">n.plots =</span> <span class="dv">6</span>,</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">plot.layout =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>), <span class="at">write.title =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/marginallEffects7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this partial dependence plots the predictions are on the scale of f(x). In this case, for the Bernoulli loss the returned value is on the log odds scale. You can see how this plot will look by plotting with the function from the package <code>gbm</code> and using the type “response”. Since we are interesting in finding out if the forest density has an impact in the presence of the Eurasian treecreeper affected we can have a look to the plot density variable <code>volAllha</code> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>gbm<span class="sc">::</span><span class="fu">plot.gbm</span>(modelBRT, <span class="at">i.var =</span> <span class="dv">3</span>, <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">ylab =</span> <span class="st">"Probability of finding a Common redstart"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/response7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It seems that there is an increase in probability of finding a Eurasian treecreeper with higher forest densities. We could also analyse the interaction effects, of forest diversity and for example forest density. The model predictions can be obtained for each pair of predictor variables, setting all other predictors to their means.</p>
<p>To plot this pairwise interactions we have to do:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>dismo<span class="sc">::</span><span class="fu">gbm.perspec</span>(modelBRT, <span class="dv">3</span>, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/pairwise%20int7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It seems that the highes chances to see a Eurasian treecreeper is in dense forests with highest tree diversity.</p>
</section>
</section>
<section id="sec-q8" class="level2">
<h2 class="anchored" data-anchor-id="sec-q8">Question 8</h2>
<ul>
<li>Is the presence of the Eurasian treecreeper affected by forest management?</li>
</ul>
<section id="fitting-a-brt-in-r-3" class="level3">
<h3 class="anchored" data-anchor-id="fitting-a-brt-in-r-3">Fitting a BRT in R</h3>
<p>In this case we want to assess the occurrence of certain species across the plots. In other words, we want to assess what is the probability of a certain species with biodiversity interest to be present in a plot based on the variables that describe the forest of that plot. In this case the response variable is <code>phoenicurus</code> that represents if the Great spotted woodpecker has been observed in this plot or not.</p>
<p>Then you need to select some variables of interest, after you have explored the data you can decide which variables you want to use to fit this model. We are proposing to select the following variables:</p>
<ul>
<li><p><code>latitude</code> as proxy for plot location or/and climate</p></li>
<li><p><code>forestManagementType</code> to assess if different management types have different impact in the presence / absence of Parus major.</p></li>
<li><p><code>volAllha</code> that is the total volume in the plot, as a proxy of how dense the plot is. Higher volumes will mean that the forest is more dense.</p></li>
<li><p><code>GiniDBH</code> showing how homogeneous the plot is in trees diameters. A value closer to 1 will mean that indicate more structural heterogeneity, lower values indicate more homogeneous plots.</p></li>
</ul>
<p>You can create a vector <code>selVar</code> in which you add the names of the selected variables. Then you only take those variables from the data that you will use to create the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select variables from the dataset for the model</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>selVar <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"certhia"</span>, <span class="st">"latitude"</span>, <span class="st">"forestManagementType"</span>,</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>            <span class="st">"volAllha"</span>, <span class="st">"GiniDBH"</span>,  <span class="st">"ShannonIndexTreeSpp"</span>, </span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Birds_rich"</span>)</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the dataset to the selected variables</span></span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>modelDataSel <span class="ot">&lt;-</span> observations[, <span class="fu">colnames</span>(observations) <span class="sc">%in%</span> selVar]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Unfortunately the amount of that we have in this dataset it is not enough to fit a BRT model for these variables. We are going to do an obviously wrong thing for the shake of being able to demonstrate how to fit a BRT model. In the next code you are going to repeat the same dataset multiple times:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>modelDataSel <span class="ot">&lt;-</span> <span class="fu">rbind</span>(modelDataSel, modelDataSel, modelDataSel, modelDataSel,</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>                      modelDataSel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now it is important to assess if the variables have the right categories. Variables should be type numeric or factor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelDataSel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    latitude     forestManagementType    volAllha          GiniDBH       
 Min.   :48.65   Length:495           Min.   :  1.681   Min.   :0.08209  
 1st Qu.:49.31   Class :character     1st Qu.:319.920   1st Qu.:0.13684  
 Median :49.40   Mode  :character     Median :434.729   Median :0.20358  
 Mean   :49.49                        Mean   :425.694   Mean   :0.25683  
 3rd Qu.:50.19                        3rd Qu.:558.355   3rd Qu.:0.37368  
 Max.   :50.34                        Max.   :777.882   Max.   :0.52852  
 ShannonIndexTreeSpp   Birds_rich        certhia      
 Min.   :0.000       Min.   :0.1694   Min.   :0.0000  
 1st Qu.:0.060       1st Qu.:0.3995   1st Qu.:0.0000  
 Median :0.280       Median :0.4679   Median :1.0000  
 Mean   :0.392       Mean   :0.4698   Mean   :0.5859  
 3rd Qu.:0.680       3rd Qu.:0.5089   3rd Qu.:1.0000  
 Max.   :1.450       Max.   :0.8360   Max.   :1.0000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Two variables are character, we assign to factor instead:</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>modelDataSel<span class="sc">$</span>forestManagementType <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(modelDataSel<span class="sc">$</span>forestManagementType)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the next step you can see how you can run the model with the selected variables and model parameters. You have a description of the models parameters in the <a href="#sec-modelBRT">Section&nbsp;4.2</a> . In this example we are going to use the default parameters for the calibration, where learning rate = 0.01 and tree complexity = 1 and cross-validation = 10-fold. However, the bag fraction is changed from the default value, 0.75, to 0.5. As a family we used the Bernoulli family, because we are predicting presence/absence per plot. These data have 495 plots, comprising 290 presence records for the Eurasian treecreeper. You can check these numbers by doing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(modelDataSel<span class="sc">$</span>certhia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
205 290 </code></pre>
</div>
</div>
<p>As a first guess you could decide there are enough data to model interactions of reasonable complexity, and a lr of about 0.01 could be a reasonable starting point. You can use the model creation function that steps forward and identifies the optimal number of trees (nt) by doing this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>family <span class="ot">&lt;-</span> <span class="st">"bernoulli"</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>    tc <span class="ot">=</span> <span class="dv">1</span>    <span class="co"># tree complexity</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>    lr <span class="ot">=</span> <span class="fl">0.01</span> <span class="co"># learning rate-shrinkage </span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>    bag <span class="ot">=</span> <span class="fl">0.5</span> <span class="co"># bag fraction</span></span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>    modelBRT <span class="ot">&lt;-</span> dismo<span class="sc">::</span><span class="fu">gbm.step</span>(<span class="at">data =</span> modelDataSel,</span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>                          <span class="co">#indices of predictor variables in data</span></span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">gbm.x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, </span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>                          <span class="co">#index of response variable in data:</span></span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a>                          <span class="at">gbm.y =</span> <span class="dv">7</span>,  </span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family =</span> family,</span>
<span id="cb86-13"><a href="#cb86-13" aria-hidden="true" tabindex="-1"></a>                          <span class="at">tree.complexity =</span> tc,</span>
<span id="cb86-14"><a href="#cb86-14" aria-hidden="true" tabindex="-1"></a>                          <span class="at">learning.rate =</span> lr,</span>
<span id="cb86-15"><a href="#cb86-15" aria-hidden="true" tabindex="-1"></a>                          <span class="at">bag.fraction =</span> bag)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/BRTmodel8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Running a model such as that described above writes progress reports to the screen, makes a graph, and returns an object containing a number of components. The R console results reports a brief model summary all the values are also retained in the model object.</p>
<p>The model is built with the default 10-fold cross-validation (CV). In the plotted graph the solid black curve is the mean, and the dotted curves 1 standard error, for the changes in predictive deviance (i.e., as measured on the excluded folds of the CV). The red line shows the minimum of the mean, and the green line the number of trees at which that occurs. The final model that is returned in the model object is built on the full data set, using the number of trees identified as optimal.</p>
<p>Ideally, you should invest time in modifying the parameters and finr the parameters that provide the models with the minimum deviance resulting from the best combination of bag, tree complexity and learning rate values. For the shake of limited timing, we will only test here the default values.</p>
</section>
<section id="model-behaviour-3" class="level3">
<h3 class="anchored" data-anchor-id="model-behaviour-3">Model behaviour</h3>
<p>You can summarized the model parameters used and the cross validation statistics from the fitted model by doing this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We make a table with the summary statistics  </span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a> results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Model parameters</span></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="at">Tree.Complexity =</span> modelBRT<span class="sc">$</span>gbm.call<span class="sc">$</span>tree.complexity, </span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a><span class="at">Learning.Rate =</span> modelBRT<span class="sc">$</span>gbm.call<span class="sc">$</span>learning.rate, </span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Bag.Fraction =</span> modelBRT<span class="sc">$</span>gbm.call<span class="sc">$</span>bag.fraction,</span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Interaction.depth =</span> modelBRT<span class="sc">$</span>interaction.depth,</span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Shrinkage =</span> modelBRT<span class="sc">$</span>shrinkage,</span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">N.trees =</span> modelBRT<span class="sc">$</span>n.trees,</span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb87-12"><a href="#cb87-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Cross validation statistics </span></span>
<span id="cb87-13"><a href="#cb87-13" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb87-14"><a href="#cb87-14" aria-hidden="true" tabindex="-1"></a><span class="do">## mean total deviance</span></span>
<span id="cb87-15"><a href="#cb87-15" aria-hidden="true" tabindex="-1"></a><span class="at">Deviance =</span> modelBRT<span class="sc">$</span>self.statistics<span class="sc">$</span>mean.resid, <span class="co"># mean residual deviance </span></span>
<span id="cb87-16"><a href="#cb87-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-17"><a href="#cb87-17" aria-hidden="true" tabindex="-1"></a><span class="at">AUC =</span> modelBRT<span class="sc">$</span>self.statistics<span class="sc">$</span>discrimination, <span class="co"># training data AUC score</span></span>
<span id="cb87-18"><a href="#cb87-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-19"><a href="#cb87-19" aria-hidden="true" tabindex="-1"></a><span class="at">Corr =</span> modelBRT<span class="sc">$</span>self.statistics<span class="sc">$</span>correlation,   <span class="co"># training data correlation</span></span>
<span id="cb87-20"><a href="#cb87-20" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb87-21"><a href="#cb87-21" aria-hidden="true" tabindex="-1"></a><span class="do">## Cross Validation statistics</span></span>
<span id="cb87-22"><a href="#cb87-22" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb87-23"><a href="#cb87-23" aria-hidden="true" tabindex="-1"></a><span class="co"># We calculate each statistic within each fold (at the identified optimal number</span></span>
<span id="cb87-24"><a href="#cb87-24" aria-hidden="true" tabindex="-1"></a><span class="co"># of trees that is calculated on the mean change in predictive deviance over all folds), </span></span>
<span id="cb87-25"><a href="#cb87-25" aria-hidden="true" tabindex="-1"></a><span class="co">#then present here the mean and standard error of those fold-based statistics.</span></span>
<span id="cb87-26"><a href="#cb87-26" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb87-27"><a href="#cb87-27" aria-hidden="true" tabindex="-1"></a><span class="at">devianceCV =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>deviance.mean,  <span class="co"># estimated cv deviance </span></span>
<span id="cb87-28"><a href="#cb87-28" aria-hidden="true" tabindex="-1"></a><span class="at">devianceCVse =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>deviance.se,  <span class="co"># estimated cv deviance se</span></span>
<span id="cb87-29"><a href="#cb87-29" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb87-30"><a href="#cb87-30" aria-hidden="true" tabindex="-1"></a><span class="at">CorrCV =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>correlation.mean,  <span class="co">#cv correlation</span></span>
<span id="cb87-31"><a href="#cb87-31" aria-hidden="true" tabindex="-1"></a><span class="at">CorrCVse =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>correlation.se,  <span class="co">#cv correlation se</span></span>
<span id="cb87-32"><a href="#cb87-32" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb87-33"><a href="#cb87-33" aria-hidden="true" tabindex="-1"></a><span class="at">AUCcv =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>discrimination.mean, <span class="co"># cv AUC score</span></span>
<span id="cb87-34"><a href="#cb87-34" aria-hidden="true" tabindex="-1"></a><span class="at">AUCcvSE =</span> modelBRT<span class="sc">$</span>cv.statistics<span class="sc">$</span>discrimination.se)  <span class="co"># cv AUC score se</span></span>
<span id="cb87-35"><a href="#cb87-35" aria-hidden="true" tabindex="-1"></a>                </span>
<span id="cb87-36"><a href="#cb87-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb87-37"><a href="#cb87-37" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">t</span>(results))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          [,1]
Tree.Complexity   1.000000e+00
Learning.Rate     1.000000e-02
Bag.Fraction      5.000000e-01
Interaction.depth 1.000000e+00
Shrinkage         1.000000e-02
N.trees           1.000000e+04
Deviance          2.743864e-01
AUC               1.000000e+00
Corr              9.724642e-01
devianceCV        3.462629e-01
devianceCVse      2.150974e-02
CorrCV            9.454600e-01
CorrCVse          9.277315e-03
AUCcv             9.985200e-01
AUCcvSE           1.480000e-03</code></pre>
</div>
</div>
</section>
<section id="model-output-analysis-3" class="level3">
<h3 class="anchored" data-anchor-id="model-output-analysis-3">Model output analysis</h3>
<p>We can look at the relative contribution of each of the predictor variables. The measures are based on the number of time the variable is selected for splitting, weighted by the improvement of the model as a result of each split averaged across all trees. The relative contribution of each of the variables is scaled so the sum is 100%, with higher numbers indicating stronger influence in the response.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables contribution </span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>modelBRT<span class="sc">$</span>contributions </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                      var   rel.inf
GiniDBH                           GiniDBH 26.740553
volAllha                         volAllha 20.784869
latitude                         latitude 20.348318
Birds_rich                     Birds_rich 16.783022
ShannonIndexTreeSpp   ShannonIndexTreeSpp 15.165081
forestManagementType forestManagementType  0.178157</code></pre>
</div>
</div>
<p>Here we can see that the two variables with the highest influence in the response are <code>GiniDBH</code> and <code>volAllhsa</code>.</p>
<p>Now we can evaluate the model behavior via partial dependence plots, showing the effect of each of the variables on the response by accounting for the average effects of all other predictors in the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>    dismo<span class="sc">::</span><span class="fu">gbm.plot</span>(modelBRT, <span class="at">n.plots =</span> <span class="dv">6</span>,</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">plot.layout =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>), <span class="at">write.title =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/marginallEffects8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this partial dependence plots the predictions are on the scale of f(x). In this case, for the Bernoulli loss the returned value is on the log odds scale. You can see how this plot will look by plotting with the function from the package <code>gbm</code> and using the type “response”. Since we are interesting in finding out if the forest density has an impact in the presence of the Eurasian treecreeper affected we can have a look to the plot density variable <code>volAllha</code> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>gbm<span class="sc">::</span><span class="fu">plot.gbm</span>(modelBRT, <span class="at">i.var =</span> <span class="dv">2</span>, <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">ylab =</span> <span class="st">"Probability of finding a Common redstart"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/response8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It seems that there is a small difference in the probability of finding the Eurasian treecreeper different management strategies. We could also analyse the interaction effects, of forest diversity and forest structual diversity. The model predictions can be obtained for each pair of predictor variables, setting all other predictors to their means.</p>
<p>To plot this pairwise interactions we have to do:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>dismo<span class="sc">::</span><span class="fu">gbm.perspec</span>(modelBRT, <span class="dv">5</span>, <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="modelEx_files/figure-html/pairwise%20int8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It seems that there are not clear pattenrs in the combined effect of forest structure diversity and forest tree species diversity.</p>
</section>
</section>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-elith2008" class="csl-entry" role="listitem">
Elith, J., J. R. Leathwick, and T. Hastie. 2008. <span>“A Working Guide to Boosted Regression Trees.”</span> <em>Journal of Animal Ecology</em> 77 (4): 802–13. <a href="https://doi.org/10.1111/j.1365-2656.2008.01390.x">https://doi.org/10.1111/j.1365-2656.2008.01390.x</a>.
</div>
<div id="ref-friedman" class="csl-entry" role="listitem">
Friedman, Jerome, Trevor Hastie, and Robert Tibshirani. n.d. <span>“ADDITIVE LOGISTIC REGRESSION: A STATISTICAL VIEW OF BOOSTING.”</span>
</div>
<div id="ref-hosek" class="csl-entry" role="listitem">
Hošek, Jan. n.d. <span>“Forest Structure and Dead Wood Properties in Six Representative Forest Areas in the Czech Republic.”</span>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>